#include "kids/vars_list.h"

namespace PROJECT_NS {

std::vector<VARIABLE_BASE*> VARIABLE_BASE::_LIST;

namespace Dimension {
std::size_t M;
std::size_t P;
std::size_t N;
std::size_t F;
std::size_t MP;
std::size_t PP;
std::size_t PN;
std::size_t PNN;
std::size_t PF;
std::size_t PFF;
std::size_t PNFF;
std::size_t NF;
std::size_t NN;
std::size_t FF;
std::size_t NFF;
std::size_t NNFF;
std::size_t Fadd1;

using sh_ref = std::vector<std::size_t*>;
Shape shape_1(1);
Shape shape_2(2);
Shape shape_X(1);
Shape shape_Nxgrid(1);
Shape shape_Nb(1);
Shape shape_M(sh_ref{&M});
Shape shape_P(sh_ref{&P});
Shape shape_N(sh_ref{&N});
Shape shape_F(sh_ref{&F});
Shape shape_Fadd1(sh_ref{&Fadd1});
Shape shape_MP(sh_ref{&M, &P});
Shape shape_PP(sh_ref{&P, &P});
Shape shape_PN(sh_ref{&P, &N});
Shape shape_PNN(sh_ref{&P, &N, &N});
Shape shape_PF(sh_ref{&P, &F});
Shape shape_PFF(sh_ref{&P, &F, &F});
Shape shape_PNFF(sh_ref{&P, &N, &F, &F});
Shape shape_NF(sh_ref{&N, &F});
Shape shape_NN(sh_ref{&N, &N});
Shape shape_FF(sh_ref{&F, &F});
Shape shape_NFF(sh_ref{&N, &F, &F});
Shape shape_NNFF(sh_ref{&N, &N, &F, &F});

void static_build_shapes() {
    assert(M > 0 && P > 0 && N > 0 && F > 0);  //
    // auxiliary dimension
    FF    = F * F;
    NFF   = N * FF;
    NF    = N * F;
    NN    = N * N;
    PP    = P * P;
    PN    = P * N;
    PNN   = P * NN;
    PF    = P * F;
    PFF   = P * FF;
    PNFF  = P * NFF;
    MP    = M * P;
    Fadd1 = F + 1;
    shape_M.static_build();
    shape_P.static_build();
    shape_N.static_build();
    shape_F.static_build();
    shape_Fadd1.static_build();
    shape_MP.static_build();
    shape_PP.static_build();
    shape_PN.static_build();
    shape_PNN.static_build();
    shape_PF.static_build();
    shape_PFF.static_build();
    shape_PNFF.static_build();
    shape_NF.static_build();
    shape_NN.static_build();
    shape_FF.static_build();
    shape_NFF.static_build();
    shape_NNFF.static_build();
}
};  // namespace Dimension

namespace DATA {

#define NAME_WRAPPER(name, shape, doc_string) name(#name, shape, doc_string)

VARIABLE<kids_real>    NAME_WRAPPER(init::Etot, &Dimension::shape_1, "total energy");
VARIABLE<kids_real>    NAME_WRAPPER(init::p, &Dimension::shape_N, "nuclear momentum");
VARIABLE<kids_real>    NAME_WRAPPER(init::x, &Dimension::shape_N, "nuclear coordinate");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::Acoeff, &Dimension::shape_P, "configuration coefficients");
VARIABLE<kids_real>    NAME_WRAPPER(integrator::E, &Dimension::shape_PF, "adiabatic energies");
VARIABLE<kids_real>    NAME_WRAPPER(integrator::Ekin, &Dimension::shape_P, "kinematic energy");
VARIABLE<kids_real>    NAME_WRAPPER(integrator::Epot, &Dimension::shape_P, "potential energy");
VARIABLE<kids_real>    NAME_WRAPPER(integrator::Etot, &Dimension::shape_P, "total energy");
VARIABLE<kids_real>    NAME_WRAPPER(integrator::GWP::L, &Dimension::shape_P, "ES used for GWP");
VARIABLE<kids_real>    NAME_WRAPPER(integrator::GWP::L1, &Dimension::shape_P, "");
VARIABLE<kids_real>    NAME_WRAPPER(integrator::GWP::L2, &Dimension::shape_P, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::GWP::R, &Dimension::shape_PP, "EV used for GWP");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::GWP::R1, &Dimension::shape_PP, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::GWP::R2, &Dimension::shape_PP, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::GWP::S1, &Dimension::shape_PP, "overlap used for GWP");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::GWP::S1h, &Dimension::shape_PP, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::GWP::S2, &Dimension::shape_PP, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::GWP::S2h, &Dimension::shape_PP, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::GWP::Sx, &Dimension::shape_PP, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::GWP::invS1h, &Dimension::shape_PP, "inversed overlap used for GWP");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::GWP::invS2h, &Dimension::shape_PP, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::Hbasis, &Dimension::shape_PP, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::Hcoeff, &Dimension::shape_PP, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::K0, &Dimension::shape_PFF, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::K1, &Dimension::shape_PFF, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::K1DA, &Dimension::shape_PFF, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::K1DD, &Dimension::shape_PFF, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::K1QA, &Dimension::shape_PFF, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::K1QD, &Dimension::shape_PFF, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::K2, &Dimension::shape_PFF, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::K2DA, &Dimension::shape_PFF, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::K2DD, &Dimension::shape_PFF, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::K2QA, &Dimension::shape_PFF, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::K2QD, &Dimension::shape_PFF, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::OpA, &Dimension::shape_FF, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::OpB, &Dimension::shape_FF, "");
VARIABLE<kids_real>    NAME_WRAPPER(integrator::P_used, &Dimension::shape_1, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::S, &Dimension::shape_PP, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::Sele, &Dimension::shape_PP, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::Snuc, &Dimension::shape_PP, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::U, &Dimension::shape_PFF, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::UXdt, &Dimension::shape_PP, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::UYdt, &Dimension::shape_PP, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::Ubranch, &Dimension::shape_FF, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::Udt, &Dimension::shape_PFF, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::Xcoeff, &Dimension::shape_P, "");
VARIABLE<kids_real>    NAME_WRAPPER(integrator::alpha, &Dimension::shape_P, "");
// VARIABLE<kids_real>    NAME_WRAPPER(integrator::alpha, &Dimension::shape_N, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::c, &Dimension::shape_PF, "electronic amplitude");
VARIABLE<kids_real>    NAME_WRAPPER(integrator::c1, &Dimension::shape_PN, "langevin coefficients 1");
VARIABLE<kids_real>    NAME_WRAPPER(integrator::c2p, &Dimension::shape_PN, "langevin coefficients 2");
VARIABLE<kids_int>     NAME_WRAPPER(integrator::clone_account, &Dimension::shape_P, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::dtAcoeff, &Dimension::shape_P, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::dtSele, &Dimension::shape_PP, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::dtlnSnuc, &Dimension::shape_PP, "");
VARIABLE<kids_real>    NAME_WRAPPER(integrator::f, &Dimension::shape_PN, "");
VARIABLE<kids_real>    NAME_WRAPPER(integrator::fadd, &Dimension::shape_PN, "");
VARIABLE<kids_real>    NAME_WRAPPER(integrator::g, &Dimension::shape_P, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::invS, &Dimension::shape_PP, "");
VARIABLE<kids_real>    NAME_WRAPPER(integrator::m, &Dimension::shape_PN, "");
VARIABLE<kids_real>    NAME_WRAPPER(integrator::minv, &Dimension::shape_PN, "");
VARIABLE<kids_real>    NAME_WRAPPER(integrator::nhc::G, &Dimension::shape_X, "");
VARIABLE<kids_real>    NAME_WRAPPER(integrator::nhc::Q, &Dimension::shape_X, "");
VARIABLE<kids_real>    NAME_WRAPPER(integrator::nhc::p, &Dimension::shape_X, "");
VARIABLE<kids_real>    NAME_WRAPPER(integrator::nhc::x, &Dimension::shape_X, "");
VARIABLE<kids_real>    NAME_WRAPPER(integrator::norm, &Dimension::shape_1, "");
VARIABLE<kids_int>     NAME_WRAPPER(integrator::occ_nuc, &Dimension::shape_P, "");
VARIABLE<kids_real>    NAME_WRAPPER(integrator::p, &Dimension::shape_PN, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::p_sign, &Dimension::shape_2, "");
VARIABLE<kids_real>    NAME_WRAPPER(integrator::param::c1, &Dimension::shape_X, "");
VARIABLE<kids_real>    NAME_WRAPPER(integrator::param::c2p, &Dimension::shape_X, "");
VARIABLE<kids_bint>    NAME_WRAPPER(integrator::pf_cross, &Dimension::shape_PF, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::rho_dual, &Dimension::shape_PFF, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::rho_ele, &Dimension::shape_PFF, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::rho_nuc, &Dimension::shape_PFF, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::rhored, &Dimension::shape_FF, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::rhored2, &Dimension::shape_FF, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::rhored3, &Dimension::shape_FF, "");
VARIABLE<kids_real>    NAME_WRAPPER(integrator::sqcIA, &Dimension::shape_1, "");
VARIABLE<kids_real>    NAME_WRAPPER(integrator::sqcID, &Dimension::shape_1, "");
VARIABLE<kids_real>    NAME_WRAPPER(integrator::sqcw, &Dimension::shape_F, "");
// VARIABLE<kids_real>    NAME_WRAPPER(integrator::sqcw, &Dimension::shape_FF, "");
// VARIABLE<kids_real>    NAME_WRAPPER(integrator::sqcw, &Dimension::shape_F, "");
VARIABLE<kids_real>    NAME_WRAPPER(integrator::sqcw0, &Dimension::shape_FF, "");
VARIABLE<kids_real>    NAME_WRAPPER(integrator::sqcwh, &Dimension::shape_FF, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::tmp::I_PP, &Dimension::shape_PP, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::tmp::MatC_PP, &Dimension::shape_PP, "");
VARIABLE<kids_real>    NAME_WRAPPER(integrator::tmp::MatR_PP, &Dimension::shape_PP, "");
VARIABLE<kids_real>    NAME_WRAPPER(integrator::tmp::TtTold, &Dimension::shape_FF, "");
VARIABLE<kids_real>    NAME_WRAPPER(integrator::tmp::direction, &Dimension::shape_N, "");
VARIABLE<kids_real>    NAME_WRAPPER(integrator::tmp::fproj, &Dimension::shape_N, "");
VARIABLE<kids_real>    NAME_WRAPPER(integrator::tmp::ftmp, &Dimension::shape_N, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::tmp::fun_diag_F, &Dimension::shape_F, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::tmp::fun_diag_P, &Dimension::shape_P, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::tmp::invexpidiagdt, &Dimension::shape_F, "");
VARIABLE<kids_real>    NAME_WRAPPER(integrator::tmp::ve, &Dimension::shape_N, "");
VARIABLE<kids_real>    NAME_WRAPPER(integrator::tmp::vedE, &Dimension::shape_FF, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::tmp::wrho, &Dimension::shape_FF, "");
VARIABLE<kids_real>    NAME_WRAPPER(integrator::veF, &Dimension::shape_FF, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::w, &Dimension::shape_P, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::w_AA, &Dimension::shape_P, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::w_AD, &Dimension::shape_P, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::w_CC, &Dimension::shape_P, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::w_CP, &Dimension::shape_P, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::w_DD, &Dimension::shape_P, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::w_PP, &Dimension::shape_P, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::ww_A, &Dimension::shape_P, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::ww_D, &Dimension::shape_P, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::wz_A, &Dimension::shape_P, "");
VARIABLE<kids_complex> NAME_WRAPPER(integrator::wz_D, &Dimension::shape_P, "");
VARIABLE<kids_real>    NAME_WRAPPER(integrator::x, &Dimension::shape_PN, "");
VARIABLE<kids_real>    NAME_WRAPPER(integrator::xgrid, &Dimension::shape_Nxgrid, "");
VARIABLE<kids_bint>    NAME_WRAPPER(iter::at_samplingstep_finally, &Dimension::shape_1, "");
VARIABLE<kids_bint>    NAME_WRAPPER(iter::at_samplingstep_initially, &Dimension::shape_1, "");
VARIABLE<kids_real>    NAME_WRAPPER(iter::dt, &Dimension::shape_1, "");
VARIABLE<kids_int>     NAME_WRAPPER(iter::dtsize, &Dimension::shape_1, "");
VARIABLE<kids_int>     NAME_WRAPPER(iter::fail_type, &Dimension::shape_1, "");
VARIABLE<kids_bint>    NAME_WRAPPER(iter::frez, &Dimension::shape_1, "");
VARIABLE<kids_int>     NAME_WRAPPER(iter::isamp, &Dimension::shape_1, "");
VARIABLE<kids_int>     NAME_WRAPPER(iter::istep, &Dimension::shape_1, "");
VARIABLE<kids_bint>    NAME_WRAPPER(iter::last_attempt, &Dimension::shape_1, "");
VARIABLE<kids_int>     NAME_WRAPPER(iter::msize, &Dimension::shape_1, "");
VARIABLE<kids_int>     NAME_WRAPPER(iter::nsamp, &Dimension::shape_1, "");
VARIABLE<kids_int>     NAME_WRAPPER(iter::nstep, &Dimension::shape_1, "");
VARIABLE<kids_int>     NAME_WRAPPER(iter::sstep, &Dimension::shape_1, "");
VARIABLE<kids_bint>    NAME_WRAPPER(iter::succ, &Dimension::shape_1, "");
VARIABLE<kids_real>    NAME_WRAPPER(iter::t, &Dimension::shape_1, "");
VARIABLE<kids_int>     NAME_WRAPPER(iter::tsize, &Dimension::shape_1, "");
VARIABLE<kids_real>    NAME_WRAPPER(last::Etot, &Dimension::shape_P, "total energy in last step");
VARIABLE<kids_complex> NAME_WRAPPER(last::c, &Dimension::shape_PF, "");
VARIABLE<kids_real>    NAME_WRAPPER(last::dV, &Dimension::shape_PNFF, "");
VARIABLE<kids_real>    NAME_WRAPPER(last::g, &Dimension::shape_P, "");
VARIABLE<kids_real>    NAME_WRAPPER(last::grad, &Dimension::shape_PN, "");
VARIABLE<kids_real>    NAME_WRAPPER(last::p, &Dimension::shape_PN, "");
VARIABLE<kids_real>    NAME_WRAPPER(last::x, &Dimension::shape_PN, "");
VARIABLE<kids_real>    NAME_WRAPPER(model::Hsys, &Dimension::shape_FF, "system part of Hamiltonian");
VARIABLE<kids_real>    NAME_WRAPPER(model::Tmod, &Dimension::shape_NN, "normalmode transformation");
VARIABLE<kids_real>    NAME_WRAPPER(model::V, &Dimension::shape_PFF, "diabatic potential of energy matrix");
VARIABLE<kids_int>     NAME_WRAPPER(model::atoms, &Dimension::shape_N, "atom indices");
VARIABLE<kids_real>    NAME_WRAPPER(model::bath::coeffs, &Dimension::shape_Nb, "");
VARIABLE<kids_real>    NAME_WRAPPER(model::bath::omegas, &Dimension::shape_Nb, "");
VARIABLE<kids_real>    NAME_WRAPPER(model::bath::p_sigma, &Dimension::shape_Nb, "");
VARIABLE<kids_real>    NAME_WRAPPER(model::bath::x_sigma, &Dimension::shape_Nb, "");
VARIABLE<kids_real>    NAME_WRAPPER(model::coupling::CL, &Dimension::shape_X, "");
VARIABLE<kids_real>    NAME_WRAPPER(model::coupling::Q, &Dimension::shape_X, "");
VARIABLE<kids_real>    NAME_WRAPPER(model::coupling::QL, &Dimension::shape_X, "");
VARIABLE<kids_real>    NAME_WRAPPER(model::coupling::Xnj, &Dimension::shape_NFF, "");
VARIABLE<kids_real>    NAME_WRAPPER(model::dV, &Dimension::shape_PNFF, "");
VARIABLE<kids_real>    NAME_WRAPPER(model::ddV, &Dimension::shape_NNFF, "");
VARIABLE<kids_real>    NAME_WRAPPER(model::f_p, &Dimension::shape_X, "");
VARIABLE<kids_real>    NAME_WRAPPER(model::f_r, &Dimension::shape_X, "");
VARIABLE<kids_real>    NAME_WRAPPER(model::f_rp, &Dimension::shape_X, "");
VARIABLE<kids_real>    NAME_WRAPPER(model::grad, &Dimension::shape_PN, "");
VARIABLE<kids_real>    NAME_WRAPPER(model::hess, &Dimension::shape_PNN, "");
VARIABLE<kids_real>    NAME_WRAPPER(model::kcoeff, &Dimension::shape_X, "");
VARIABLE<kids_real>    NAME_WRAPPER(model::lcoeff, &Dimension::shape_X, "");
VARIABLE<kids_real>    NAME_WRAPPER(model::mass, &Dimension::shape_N, "");
VARIABLE<kids_real>    NAME_WRAPPER(model::p0, &Dimension::shape_N, "");
VARIABLE<kids_real>    NAME_WRAPPER(model::p_sigma, &Dimension::shape_N, "");
VARIABLE<kids_real>    NAME_WRAPPER(model::rep::E, &Dimension::shape_PF, "");
VARIABLE<kids_complex> NAME_WRAPPER(model::rep::H, &Dimension::shape_PFF, "");
VARIABLE<kids_real>    NAME_WRAPPER(model::rep::L, &Dimension::shape_PF, "");
VARIABLE<kids_complex> NAME_WRAPPER(model::rep::R, &Dimension::shape_PFF, "");
VARIABLE<kids_real>    NAME_WRAPPER(model::rep::T, &Dimension::shape_PFF, "");
VARIABLE<kids_real>    NAME_WRAPPER(model::rep::Told, &Dimension::shape_PFF, "");
VARIABLE<kids_real>    NAME_WRAPPER(model::rep::dE, &Dimension::shape_PNFF, "");
VARIABLE<kids_real>    NAME_WRAPPER(model::rep::ddE, &Dimension::shape_NNFF, "");
VARIABLE<kids_real>    NAME_WRAPPER(model::rep::nac, &Dimension::shape_NFF, "");
VARIABLE<kids_real>    NAME_WRAPPER(model::rep::nac_prev, &Dimension::shape_NFF, "");
VARIABLE<kids_real>    NAME_WRAPPER(model::vpes, &Dimension::shape_P, "scalar potential of energy");
VARIABLE<kids_real>    NAME_WRAPPER(model::w, &Dimension::shape_N, "");
VARIABLE<kids_real>    NAME_WRAPPER(model::x0, &Dimension::shape_N, "initial cencter of coordinate");
VARIABLE<kids_real>    NAME_WRAPPER(model::x_sigma, &Dimension::shape_N, "initial width of coordinate");
VARIABLE<kids_int>     NAME_WRAPPER(random::seed, &Dimension::shape_X, "");
};  // namespace DATA

};  // namespace PROJECT_NS