!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.10 (r5717) - 10 Nov 2015 15:36
!
!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.10 (r5717) - 10 Nov 2015 15:36
!
!
!   System:    H2O2
!   Functional Form: 
!   Common name:  Koput-Carter-Handy
!   Number of derivatives:  1
!   Number of bodies:  4
!   Number of electronic surfaces:  1
!   Interface:  Section-2
!
!   References: Koput, J.; Carter, S.; Handy, N. C.;
!               J. Phys. Chem. A, 102 (1998) 6325.
!
!   Notes:
MODULE PES_H2O2
  USE DIFFSIZES
!  Hint: nbdirsmax should be the maximum number of differentiation directions
  IMPLICIT NONE
!**************************************************************************
!size of internal coordinates(3*N-6)
  INTEGER, PARAMETER :: nr=6
!size of cartesian coordinates (3N)
  INTEGER, PARAMETER :: nx=12
  REAL*8, PARAMETER :: rohlow=1.0d0
  REAL*8, PARAMETER :: rohhigh=4.0d0
  REAL*8, PARAMETER :: roolow=1.8d0
  REAL*8, PARAMETER :: roohigh=4.0d0
  REAL*8, PARAMETER :: rhhlow=0.7d0
  REAL*8, PARAMETER :: pi=4.d0*ATAN(1.d0)
  REAL*8, PARAMETER :: rm_oo=1.456199d0
  REAL*8, PARAMETER :: rm_oh=0.962755d0
  REAL*8, PARAMETER :: angle_ooh=100.9059d0*pi/180.d0
  INTEGER :: ind1(152), ind2(152), ind3(152), ind4(152)
  INTEGER :: ind5(152), ind6(152)
  DOUBLE PRECISION :: coeff(152)
  REAL*8, PARAMETER :: zoe=3.995139982058d-3
  DATA ind1 /0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0&
&      , 3, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 1, 2, 1, 0, 2, 0, 1, 0, 2, &
&      0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 4, 0, 0, 0, 2, 0, 0, 0&
&      , 2, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 1, 3, 1, 0, 3, 0, 0, 0, 1, 1, &
&      0, 1, 0, 0, 1, 0, 2, 0, 2, 0, 0, 0, 1, 1, 2, 0, 1, 0, 1, 0, 0, 1&
&      , 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 3, 0, 0, 0, &
&      2, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1&
&      , 0, 0, 0/
  DATA ind2 /0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0&
&      , 0, 3, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 2, 1, 0, 1, 0, 2, 0, 1, 0, &
&      2, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 4, 0, 0, 0, 2, 0, 0&
&      , 0, 2, 0, 0, 1, 0, 0, 0, 3, 0, 0, 3, 1, 0, 1, 0, 3, 0, 0, 1, 0, &
&      1, 0, 1, 0, 0, 1, 0, 2, 0, 2, 0, 0, 1, 1, 0, 2, 0, 1, 0, 1, 0, 0&
&      , 1, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 3, 0, 0, &
&      0, 2, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0&
&      , 1, 0, 0/
  DATA ind3 /0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 3&
&      , 0, 0, 0, 0, 2, 2, 2, 2, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, &
&      0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 4, 0, 0, 0, 0, 2, 2, 2, 2&
&      , 0, 0, 0, 3, 3, 3, 3, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, &
&      2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0&
&      , 0, 0, 0, 2, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 3, 0, 0, 0, 0, &
&      1, 1, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0&
&      , 0, 0, 0/
  DATA ind4 /0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0&
&      , 0, 0, 3, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 2, 0, 1, 0, 0, 2, 0, &
&      1, 1, 2, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 4, 0, 0, 0, 2, 0&
&      , 2, 0, 2, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 3, 0, 1, 0, 1, 3, 0, 1, &
&      0, 0, 1, 1, 2, 0, 1, 0, 0, 1, 1, 2, 2, 0, 1, 1, 1, 2, 2, 1, 0, 0&
&      , 0, 1, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 3, 0, &
&      0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0&
&      , 0, 1, 0/
  DATA ind5 /0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0&
&      , 0, 0, 0, 3, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 2, 0, 1, 2, 0, 1, &
&      0, 2, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 4, 0, 0, 0, 2&
&      , 0, 2, 2, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 3, 0, 1, 3, 1, 0, 0, &
&      1, 1, 0, 1, 0, 2, 0, 1, 1, 0, 2, 1, 0, 2, 1, 1, 2, 1, 1, 2, 0, 0&
&      , 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 3, &
&      0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0&
&      , 0, 0, 1/
  DATA ind6 /1, 2, 3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0&
&      , 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, &
&      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0&
&      , 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, &
&      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1&
&      , 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, &
&      1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3&
&      , 3, 3, 3/
  DATA coeff /0.00482409d0, 0.00325127d0, 0.00026630d0, 0.00004135d0, &
&      1.08154998d0, 0.86097723d0, 0.86097723d0, 0.11016112d0, &
&      0.11016112d0, -0.03637740d0, -0.03637740d0, 0.17491854d0, &
&      0.17491854d0, 0.00057054d0, -0.00137967d0, -0.00137967d0, &
&      0.00062152d0, 0.00062152d0, 0.01375726d0, -1.15691421d0, -&
&      0.25495918d0, -0.25495918d0, -0.02272830d0, -0.02272830d0, -&
&      0.18381415d0, -0.18381415d0, -0.34627237d0, -0.34627237d0, &
&      0.13974588d0, 0.13974588d0, -0.27290455d0, -0.27290455d0, -&
&      0.00674721d0, -0.00674721d0, -0.02179545d0, -0.02179545d0, -&
&      0.02125643d0, -0.02125643d0, -0.00491968d0, -0.00491968d0, &
&      0.00233773d0, 0.00233773d0, -0.00050066d0, -0.00050066d0, &
&      0.01817536d0, -0.04666009d0, -0.04666009d0, -0.02424748d0, -&
&      0.02424748d0, -0.01727148d0, -0.00420506d0, -0.00420506d0, -&
&      0.00647944d0, -0.00647944d0, -1.06749007d0, -0.35741007d0, -&
&      0.35741007d0, -0.00796836d0, -0.00796836d0, -0.42556742d0, -&
&      0.42556742d0, 0.06278896d0, 0.06278896d0, -0.04010419d0, -&
&      0.04010419d0, -0.00993912d0, 0.47562894d0, 0.47562894d0, -&
&      0.40830627d0, -0.40830627d0, 0.22073222d0, 0.22073222d0, &
&      0.07828212d0, 0.07828212d0, -0.02954687d0, -0.02954687d0, &
&      0.03057888d0, 0.03057888d0, -0.06363999d0, -0.06363999d0, -&
&      0.00373964d0, -0.00373964d0, -0.04114668d0, 0.11249614d0, &
&      0.11249614d0, 0.02616679d0, 0.02616679d0, -0.07824425d0, &
&      0.04266205d0, 0.04266205d0, -0.07420432d0, -0.07420432d0, -&
&      0.08251268d0, -0.08251268d0, 0.00270940d0, 0.00270940d0, &
&      0.00199953d0, 0.00199953d0, -0.01292325d0, -0.01292325d0, -&
&      0.02074323d0, -0.02074323d0, -0.00789732d0, -0.00789732d0, -&
&      0.01435326d0, -0.00180710d0, -0.00180710d0, -0.01135671d0, -&
&      0.01135671d0, 0.00020655d0, -0.00492533d0, -0.00492533d0, &
&      0.00270990d0, 0.00270990d0, 0.00376086d0, 0.00376086d0, &
&      0.00044732d0, 0.00044732d0, 0.00569979d0, -0.00244774d0, -&
&      0.00244774d0, -0.02065564d0, 0.05249331d0, -0.02490299d0, -&
&      0.02490299d0, 0.00391460d0, 0.00391460d0, 0.08893744d0, &
&      0.08893744d0, -0.01051618d0, 0.00120479d0, 0.00120479d0, -&
&      0.00111888d0, -0.00111888d0, 0.00884757d0, 0.00416289d0, &
&      0.00416289d0, 0.00126763d0, 0.00126763d0, -0.00706563d0, -&
&      0.00706563d0, -0.00840146d0, -0.00840146d0, -0.00139219d0, &
&      0.00801673d0, 0.00801673d0, 0.00463860d0, -0.00096051d0, &
&      0.00019906d0, 0.00019906d0, -0.00057576d0, -0.00057576d0/

CONTAINS
!  Differentiation of surf_b in forward (tangent) mode (with options multiDirectional i4 dr8 r4):
!   variations   of useful results: xb vb
!   with respect to varying inputs: x vb
!   RW status of diff variables: xb:out x:in vb:in-zero
!  Differentiation of surf in reverse (adjoint) mode (with options i4 dr8 r4):
!   gradient     of useful results: v
!   with respect to varying inputs: v x
!   RW status of diff variables: v:in-zero x:out
!..................................
!@the unit of input: x is Angstrom
!the unit of output:
!@ pot: hartree 
!@ dv: hartee/A
!@ ddv: hartree/A^2
  SUBROUTINE SURF_B_DV(x, xd, xb, xbd, v, vb, vbd, nbdirs) bind(c, name="pes_h2o2_surf_b_dv")
    USE DIFFSIZES
!  Hint: nbdirsmax should be the maximum number of differentiation directions
    IMPLICIT NONE
    REAL*8 :: v, x(nx)
    REAL*8 :: xd(nbdirsmax, nx)
    REAL*8 :: vb, xb(nx)
    REAL*8 :: vbd(nbdirsmax), xbd(nbdirsmax, nx)
    INTEGER :: i
!integer,parameter::nhes=nx*(nx+1)/2
!integer :: i,j
!integer,parameter::row(nhes) =(/ ( (i,i=j,nx),j=1,nx) /)
!integer,parameter::col(nhes) =(/ ( (j,i=j,nx),j=1,nx) /)
!real(8) ::ddv(nhes)
    REAL*8 :: q1p(0:4), q2p(0:4), q3p(0:4), q4p(0:4), q5p(0:4), q6p(0:4)
    REAL*8 :: q1pd(nbdirsmax, 0:4), q2pd(nbdirsmax, 0:4), q3pd(nbdirsmax&
&   , 0:4), q4pd(nbdirsmax, 0:4), q5pd(nbdirsmax, 0:4), q6pd(nbdirsmax, &
&   0:4)
    REAL*8 :: q1pb(0:4), q2pb(0:4), q3pb(0:4), q4pb(0:4), q5pb(0:4), &
&   q6pb(0:4)
    REAL*8 :: q1pbd(nbdirsmax, 0:4), q2pbd(nbdirsmax, 0:4), q3pbd(&
&   nbdirsmax, 0:4), q4pbd(nbdirsmax, 0:4), q5pbd(nbdirsmax, 0:4), q6pbd&
&   (nbdirsmax, 0:4)
    REAL*8 :: n, n1, n2
    REAL*8, DIMENSION(nbdirsmax) :: nd, n1d, n2d
    REAL*8 :: nb, n1b, n2b
    REAL*8, DIMENSION(nbdirsmax) :: nbd, n1bd, n2bd
    REAL*8 :: rh1o1, ro1o2, ro2h2
    REAL*8, DIMENSION(nbdirsmax) :: rh1o1d, ro1o2d, ro2h2d
    REAL*8 :: rh1o1b, ro1o2b, ro2h2b
    REAL*8, DIMENSION(nbdirsmax) :: rh1o1bd, ro1o2bd, ro2h2bd
    REAL*8 :: d1, d2, d, ah1oo, aooh2, thooh
    REAL*8, DIMENSION(nbdirsmax) :: d1d, d2d, dd, ah1ood, aooh2d
    REAL*8 :: d1b, d2b, db, ah1oob, aooh2b
    REAL*8, DIMENSION(nbdirsmax) :: d1bd, d2bd, dbd, ah1oobd, aooh2bd
    REAL*8 :: xcomp1, ycomp1, zcomp1
    REAL*8, DIMENSION(nbdirsmax) :: xcomp1d, ycomp1d, zcomp1d
    REAL*8 :: xcomp1b, ycomp1b, zcomp1b
    REAL*8, DIMENSION(nbdirsmax) :: xcomp1bd, ycomp1bd, zcomp1bd
    REAL*8 :: xcomp2, ycomp2, zcomp2
    REAL*8, DIMENSION(nbdirsmax) :: xcomp2d, ycomp2d, zcomp2d
    REAL*8 :: xcomp2b, ycomp2b, zcomp2b
    REAL*8, DIMENSION(nbdirsmax) :: xcomp2bd, ycomp2bd, zcomp2bd
    REAL*8 :: xcomp3, ycomp3, zcomp3
    REAL*8, DIMENSION(nbdirsmax) :: xcomp3d, ycomp3d, zcomp3d
    REAL*8 :: xcomp3b, ycomp3b, zcomp3b
    REAL*8, DIMENSION(nbdirsmax) :: xcomp3bd, ycomp3bd, zcomp3bd
    REAL*8 :: xcomp4, ycomp4, zcomp4
    REAL*8, DIMENSION(nbdirsmax) :: xcomp4d, ycomp4d, zcomp4d
    REAL*8 :: xcomp4b, ycomp4b, zcomp4b
    REAL*8, DIMENSION(nbdirsmax) :: xcomp4bd, ycomp4bd, zcomp4bd
    REAL*8 :: x_normal1, y_normal1, z_normal1
    REAL*8, DIMENSION(nbdirsmax) :: x_normal1d, y_normal1d, z_normal1d
    REAL*8 :: x_normal1b, y_normal1b, z_normal1b
    REAL*8, DIMENSION(nbdirsmax) :: x_normal1bd, y_normal1bd, &
&   z_normal1bd
    REAL*8 :: x_normal2, y_normal2, z_normal2
    REAL*8, DIMENSION(nbdirsmax) :: x_normal2d, y_normal2d, z_normal2d
    REAL*8 :: x_normal2b, y_normal2b, z_normal2b
    REAL*8, DIMENSION(nbdirsmax) :: x_normal2bd, y_normal2bd, &
&   z_normal2bd
    REAL*8 :: q1, q2, q3, q4, q5, q6
    REAL*8, DIMENSION(nbdirsmax) :: q1d, q2d, q3d, q4d, q5d
    REAL*8 :: q1b, q2b, q3b, q4b, q5b
    REAL*8, DIMENSION(nbdirsmax) :: q1bd, q2bd, q3bd, q4bd, q5bd
!real(8)::vH1O1(3),vO1O2(3),vO2H2(3),vH1O2(3),vO1H2(3),vH1H2(3)
    REAL*8 :: c1, c2, c3, c4, c5, c6, c7, c8, c9, c10
    REAL*8, DIMENSION(nbdirsmax) :: c1d, c2d, c3d, c4d, c5d, c6d, c7d, &
&   c8d, c9d, c10d
    REAL*8 :: c1b, c2b, c3b, c4b, c5b, c6b, c7b, c8b, c9b, c10b
    REAL*8, DIMENSION(nbdirsmax) :: c1bd, c2bd, c3bd, c4bd, c5bd, c6bd, &
&   c7bd, c8bd, c9bd, c10bd
    REAL*8 :: c11, c12, c13, c14, c15
    REAL*8, DIMENSION(nbdirsmax) :: c11d, c12d, c13d, c14d, c15d
    REAL*8 :: c11b, c12b, c13b, c14b, c15b
    REAL*8, DIMENSION(nbdirsmax) :: c11bd, c12bd, c13bd, c14bd, c15bd
    REAL*8 :: cost
    INTRINSIC SQRT
    INTRINSIC ACOS
    INTEGER :: branch
    REAL*8 :: temp3
    REAL*8, DIMENSION(nbdirsmax) :: temp3d
    REAL*8 :: temp2
    REAL*8, DIMENSION(nbdirsmax) :: temp2d
    REAL*8 :: temp1
    REAL*8, DIMENSION(nbdirsmax) :: temp1d
    REAL*8 :: temp0
    REAL*8, DIMENSION(nbdirsmax) :: temp0d
    REAL*8 :: cosqb
    REAL*8, DIMENSION(nbdirsmax) :: cosqbd
    REAL*8 :: tempb7
    REAL*8, DIMENSION(nbdirsmax) :: tempb7d
    REAL*8 :: tempb6
    REAL*8, DIMENSION(nbdirsmax) :: tempb6d
    REAL*8 :: tempb5
    REAL*8, DIMENSION(nbdirsmax) :: tempb5d
    REAL*8 :: tempb4
    REAL*8, DIMENSION(nbdirsmax) :: tempb4d
    REAL*8 :: tempb3
    REAL*8, DIMENSION(nbdirsmax) :: tempb3d
    REAL*8 :: tempb2
    REAL*8, DIMENSION(nbdirsmax) :: tempb2d
    REAL*8 :: tempb1
    REAL*8, DIMENSION(nbdirsmax) :: tempb1d
    REAL*8 :: tempb0
    REAL*8, DIMENSION(nbdirsmax) :: tempb0d
    REAL*8 :: cosq
    REAL*8, DIMENSION(nbdirsmax) :: cosqd
    REAL*8 :: tempb
    REAL*8, DIMENSION(nbdirsmax) :: tempbd
    REAL*8 :: temp
    REAL*8, DIMENSION(nbdirsmax) :: tempd
    REAL*8 :: temp4
    REAL*8, DIMENSION(nbdirsmax) :: temp4d
    EXTERNAL PUSHCONTROL1B
    EXTERNAL PUSHREAL8
    EXTERNAL PUSHREAL8_DV
    EXTERNAL POPREAL8
    EXTERNAL POPREAL8_DV
    EXTERNAL POPCONTROL1B
    REAL*8 :: arg1
    REAL*8, DIMENSION(nbdirsmax) :: arg1d
    REAL*8 :: result1
    REAL*8, DIMENSION(nbdirsmax) :: result1d
    REAL*8 :: arg2
    REAL*8, DIMENSION(nbdirsmax) :: arg2d
    REAL*8 :: result2
    REAL*8, DIMENSION(nbdirsmax) :: result2d
    INTEGER :: nd0
    INTEGER :: nbdirs
    c1 = x(1) - x(4)
    c2 = x(2) - x(5)
    c3 = x(3) - x(6)
    c4 = x(4) - x(7)
    c5 = x(5) - x(8)
    c6 = x(6) - x(9)
    c7 = x(7) - x(10)
    c8 = x(8) - x(11)
    c9 = x(9) - x(12)
    c10 = x(1) - x(7)
    c11 = x(2) - x(8)
    c12 = x(3) - x(9)
    c13 = x(4) - x(10)
    c14 = x(5) - x(11)
    c15 = x(6) - x(12)
    arg1 = c1**2 + c2**2 + c3**2
    xcomp1 = -c1
    ycomp1 = -c2
    zcomp1 = -c3
    xcomp2 = c10
    ycomp2 = c11
    zcomp2 = c12
    x_normal1 = ycomp1*zcomp2 - zcomp1*ycomp2
    y_normal1 = zcomp1*xcomp2 - xcomp1*zcomp2
    z_normal1 = xcomp1*ycomp2 - ycomp1*xcomp2
    xcomp3 = -c4
    ycomp3 = -c5
    zcomp3 = -c6
    xcomp4 = c13
    ycomp4 = c14
    zcomp4 = c15
    x_normal2 = ycomp3*zcomp4 - zcomp3*ycomp4
    y_normal2 = zcomp3*xcomp4 - xcomp3*zcomp4
    z_normal2 = xcomp3*ycomp4 - ycomp3*xcomp4
    arg2 = x_normal2*x_normal2 + y_normal2*y_normal2 + z_normal2*&
&     z_normal2
    DO nd0=1,nbdirs
! vector
      c1d(nd0) = xd(nd0, 1) - xd(nd0, 4)
      c2d(nd0) = xd(nd0, 2) - xd(nd0, 5)
      c3d(nd0) = xd(nd0, 3) - xd(nd0, 6)
      c4d(nd0) = xd(nd0, 4) - xd(nd0, 7)
      c5d(nd0) = xd(nd0, 5) - xd(nd0, 8)
      c6d(nd0) = xd(nd0, 6) - xd(nd0, 9)
      c7d(nd0) = xd(nd0, 7) - xd(nd0, 10)
      c8d(nd0) = xd(nd0, 8) - xd(nd0, 11)
      c9d(nd0) = xd(nd0, 9) - xd(nd0, 12)
      c10d(nd0) = xd(nd0, 1) - xd(nd0, 7)
      c11d(nd0) = xd(nd0, 2) - xd(nd0, 8)
      c12d(nd0) = xd(nd0, 3) - xd(nd0, 9)
      c13d(nd0) = xd(nd0, 4) - xd(nd0, 10)
      c14d(nd0) = xd(nd0, 5) - xd(nd0, 11)
      c15d(nd0) = xd(nd0, 6) - xd(nd0, 12)
!c16=x(1)-x(10)
!c17=x(2)-x(11)
!c18=x(3)-x(12)
!
! H1 -- O1 -- O2 -- H2
!   rH1O1 rO1O2 rO2H2
! 
!  angle H1O1O2 = AH1OO
!  angle O1O2H2 = AOOH2
!
!  TORSION HOOH = THOOH
      arg1d(nd0) = 2*c1*c1d(nd0) + 2*c2*c2d(nd0) + 2*c3*c3d(nd0)
      IF (arg1 .EQ. 0.0) THEN
        rh1o1d(nd0) = 0.0_8
      ELSE
        rh1o1d(nd0) = arg1d(nd0)/(2.0*SQRT(arg1))
      END IF
      arg1d(nd0) = 2*c4*c4d(nd0) + 2*c5*c5d(nd0) + 2*c6*c6d(nd0)
! The potential can give weird values for unusual geometries
! replace with some high value in these unphysical regions and
! then exit
!
      n1d(nd0) = -(c4d(nd0)*c1+c4*c1d(nd0)+c5d(nd0)*c2+c5*c2d(nd0)+c6d(&
&       nd0)*c3+c6*c3d(nd0))
      n2d(nd0) = -(c7d(nd0)*c4+c7*c4d(nd0)+c8d(nd0)*c5+c8*c5d(nd0)+c9d(&
&       nd0)*c6+c9*c6d(nd0))
! Calculate torsion angle HOOH
! X(4) - X(1)
      xcomp1d(nd0) = -c1d(nd0)
! X(5) - X(2)
      ycomp1d(nd0) = -c2d(nd0)
! X(6) - X(3)
      zcomp1d(nd0) = -c3d(nd0)
      xcomp2d(nd0) = c10d(nd0)
      ycomp2d(nd0) = c11d(nd0)
      zcomp2d(nd0) = c12d(nd0)
      x_normal1d(nd0) = ycomp1d(nd0)*zcomp2 + ycomp1*zcomp2d(nd0) - &
&       zcomp1d(nd0)*ycomp2 - zcomp1*ycomp2d(nd0)
      y_normal1d(nd0) = zcomp1d(nd0)*xcomp2 + zcomp1*xcomp2d(nd0) - &
&       xcomp1d(nd0)*zcomp2 - xcomp1*zcomp2d(nd0)
      z_normal1d(nd0) = xcomp1d(nd0)*ycomp2 + xcomp1*ycomp2d(nd0) - &
&       ycomp1d(nd0)*xcomp2 - ycomp1*xcomp2d(nd0)
! X(7) - X(4) 
      xcomp3d(nd0) = -c4d(nd0)
! X(8) - X(5) 
      ycomp3d(nd0) = -c5d(nd0)
! X(9) - X(6)
      zcomp3d(nd0) = -c6d(nd0)
      xcomp4d(nd0) = c13d(nd0)
      ycomp4d(nd0) = c14d(nd0)
      zcomp4d(nd0) = c15d(nd0)
      x_normal2d(nd0) = ycomp3d(nd0)*zcomp4 + ycomp3*zcomp4d(nd0) - &
&       zcomp3d(nd0)*ycomp4 - zcomp3*ycomp4d(nd0)
      y_normal2d(nd0) = zcomp3d(nd0)*xcomp4 + zcomp3*xcomp4d(nd0) - &
&       xcomp3d(nd0)*zcomp4 - xcomp3*zcomp4d(nd0)
      z_normal2d(nd0) = xcomp3d(nd0)*ycomp4 + xcomp3*ycomp4d(nd0) - &
&       ycomp3d(nd0)*xcomp4 - ycomp3*xcomp4d(nd0)
      nd(nd0) = x_normal1d(nd0)*x_normal2 + x_normal1*x_normal2d(nd0) + &
&       y_normal1d(nd0)*y_normal2 + y_normal1*y_normal2d(nd0) + &
&       z_normal1d(nd0)*z_normal2 + z_normal1*z_normal2d(nd0)
      arg2d(nd0) = x_normal2d(nd0)*x_normal2 + x_normal2*x_normal2d(nd0)&
&       + y_normal2d(nd0)*y_normal2 + y_normal2*y_normal2d(nd0) + &
&       z_normal2d(nd0)*z_normal2 + z_normal2*z_normal2d(nd0)
      IF (arg2 .EQ. 0.0) THEN
        result2d(nd0) = 0.0_8
      ELSE
        result2d(nd0) = arg2d(nd0)/(2.0*SQRT(arg2))
      END IF
    END DO
    rh1o1 = SQRT(arg1)
    arg1 = c4**2 + c5**2 + c6**2
    ro1o2 = SQRT(arg1)
    DO nd0=1,nbdirs
      IF (arg1 .EQ. 0.0) THEN
        ro1o2d(nd0) = 0.0_8
      ELSE
        ro1o2d(nd0) = arg1d(nd0)/(2.0*SQRT(arg1))
      END IF
      arg1d(nd0) = 2*c7*c7d(nd0) + 2*c8*c8d(nd0) + 2*c9*c9d(nd0)
      d1d(nd0) = ro1o2d(nd0)*rh1o1 + ro1o2*rh1o1d(nd0)
    END DO
    arg1 = c7**2 + c8**2 + c9**2
    ro2h2 = SQRT(arg1)
    n1 = -(c4*c1+c5*c2+c6*c3)
    d1 = ro1o2*rh1o1
    DO nd0=1,nbdirs
      IF (arg1 .EQ. 0.0) THEN
        ro2h2d(nd0) = 0.0_8
      ELSE
        ro2h2d(nd0) = arg1d(nd0)/(2.0*SQRT(arg1))
      END IF
      arg1d(nd0) = (n1d(nd0)*d1-n1*d1d(nd0))/d1**2
      d2d(nd0) = ro2h2d(nd0)*ro1o2 + ro2h2*ro1o2d(nd0)
    END DO
    arg1 = n1/d1
    n2 = -(c7*c4+c8*c5+c9*c6)
    d2 = ro2h2*ro1o2
    DO nd0=1,nbdirs
      IF (arg1 .EQ. 1.0 .OR. arg1 .EQ. (-1.0)) THEN
        ah1ood(nd0) = 0.0_8
      ELSE
        ah1ood(nd0) = -(arg1d(nd0)/SQRT(1.0-arg1**2))
      END IF
      arg1d(nd0) = (n2d(nd0)*d2-n2*d2d(nd0))/d2**2
    END DO
    ah1oo = ACOS(arg1)
    arg1 = n2/d2
    DO nd0=1,nbdirs
      IF (arg1 .EQ. 1.0 .OR. arg1 .EQ. (-1.0)) THEN
        aooh2d(nd0) = 0.0_8
      ELSE
        aooh2d(nd0) = -(arg1d(nd0)/SQRT(1.0-arg1**2))
      END IF
      arg1d(nd0) = x_normal1d(nd0)*x_normal1 + x_normal1*x_normal1d(nd0)&
&       + y_normal1d(nd0)*y_normal1 + y_normal1*y_normal1d(nd0) + &
&       z_normal1d(nd0)*z_normal1 + z_normal1*z_normal1d(nd0)
    END DO
    aooh2 = ACOS(arg1)
    n = x_normal1*x_normal2 + y_normal1*y_normal2 + z_normal1*z_normal2
    arg1 = x_normal1*x_normal1 + y_normal1*y_normal1 + z_normal1*&
&     z_normal1
    result1 = SQRT(arg1)
    result2 = SQRT(arg2)
    d = result1*result2
    DO nd0=1,nbdirs
      IF (arg1 .EQ. 0.0) THEN
        result1d(nd0) = 0.0_8
      ELSE
        result1d(nd0) = arg1d(nd0)/(2.0*SQRT(arg1))
      END IF
      dd(nd0) = result1d(nd0)*result2 + result1*result2d(nd0)
      cosqd(nd0) = (nd(nd0)*d-n*dd(nd0))/d**2
    END DO
    cosq = n/d
    IF (cosq .GT. 1d0) THEN
      cosq = 1d0
      CALL PUSHCONTROL1B(0)
      DO nd0=1,nbdirs
        cosqd(nd0) = 0.0_8
      END DO
    ELSE
      CALL PUSHCONTROL1B(1)
    END IF
    IF (cosq .LT. -1d0) THEN
      cosq = -1d0
      CALL PUSHCONTROL1B(0)
      DO nd0=1,nbdirs
        cosqd(nd0) = 0.0_8
      END DO
    ELSE
      CALL PUSHCONTROL1B(1)
    END IF
    DO nd0=1,nbdirs
! in radians
!R1 =  RH1O1              
!R2 =  RO1O2             
!R3 =  RO2H2         
!A1 =  AH1OO          
!A2 =  AOOH2              
!Q6 =  THOOH  
! Q1,Q2, and Q3 represent the stretching modes
! Q4 and Q5  are the bending modes
! Q6 is the torsional mode 
! Q1, Q2, Q3 are dimensionless, Q4, Q5, and Q6 are in radians
      q3d(nd0) = (ro1o2d(nd0)*ro1o2-(ro1o2-rm_oo)*ro1o2d(nd0))/ro1o2**2
      q1d(nd0) = (rh1o1d(nd0)*rh1o1-(rh1o1-rm_oh)*rh1o1d(nd0))/rh1o1**2
      q2d(nd0) = (ro2h2d(nd0)*ro2h2-(ro2h2-rm_oh)*ro2h2d(nd0))/ro2h2**2
      q4d(nd0) = ah1ood(nd0)
      q5d(nd0) = aooh2d(nd0)
    END DO
    q3 = (ro1o2-rm_oo)/ro1o2
    q1 = (rh1o1-rm_oh)/rh1o1
    q2 = (ro2h2-rm_oh)/ro2h2
    q4 = ah1oo - angle_ooh
    q5 = aooh2 - angle_ooh
    q1p(0) = 1.d0
    q2p(0) = 1.d0
    q3p(0) = 1.d0
    q4p(0) = 1.d0
    q5p(0) = 1.d0
    q6p(0) = 1.d0
    DO nd0=1,nbdirs
      q4pd(nd0, :) = 0.0_8
      q1pd(nd0, :) = 0.0_8
      q5pd(nd0, :) = 0.0_8
      q2pd(nd0, :) = 0.0_8
      q3pd(nd0, :) = 0.0_8
    END DO
    DO i=1,4
! q1**i
      CALL PUSHREAL8_DV(q1p(i), q1pd(:, i), nbdirs)
! q2**i
      CALL PUSHREAL8_DV(q2p(i), q2pd(:, i), nbdirs)
! q3**i
      CALL PUSHREAL8_DV(q3p(i), q3pd(:, i), nbdirs)
! q4**i
      CALL PUSHREAL8_DV(q4p(i), q4pd(:, i), nbdirs)
! q5**i
      CALL PUSHREAL8_DV(q5p(i), q5pd(:, i), nbdirs)
      DO nd0=1,nbdirs
        q1pd(nd0, i) = q1pd(nd0, i-1)*q1 + q1p(i-1)*q1d(nd0)
        q2pd(nd0, i) = q2pd(nd0, i-1)*q2 + q2p(i-1)*q2d(nd0)
        q3pd(nd0, i) = q3pd(nd0, i-1)*q3 + q3p(i-1)*q3d(nd0)
        q4pd(nd0, i) = q4pd(nd0, i-1)*q4 + q4p(i-1)*q4d(nd0)
        q5pd(nd0, i) = q5pd(nd0, i-1)*q5 + q5p(i-1)*q5d(nd0)
      END DO
      q1p(i) = q1p(i-1)*q1
      q2p(i) = q2p(i-1)*q2
      q3p(i) = q3p(i-1)*q3
      q4p(i) = q4p(i-1)*q4
      q5p(i) = q5p(i-1)*q5
    END DO
    DO nd0=1,nbdirs
! cos(q6) 
      q6pd(nd0, :) = 0.0_8
      q6pd(nd0, 1) = cosqd(nd0)
    END DO
    q6p(1) = cosq
! cos2q
    CALL PUSHREAL8_DV(q6p(2), q6pd(:, 2), nbdirs)
    DO nd0=1,nbdirs
      q6pd(nd0, 2) = 2d0*(q6pd(nd0, 1)*q6p(1)+q6p(1)*q6pd(nd0, 1))
    END DO
    q6p(2) = 2d0*q6p(1)*q6p(1) - 1d0
! cos3q
    CALL PUSHREAL8_DV(q6p(3), q6pd(:, 3), nbdirs)
    DO nd0=1,nbdirs
      q6pd(nd0, 3) = q6pd(nd0, 1)*(2d0*q6p(2)-1d0) + q6p(1)*2d0*q6pd(nd0&
&       , 2)
    END DO
    q6p(3) = q6p(1)*(2d0*q6p(2)-1d0)
! cos4q
    CALL PUSHREAL8_DV(q6p(4), q6pd(:, 4), nbdirs)
    DO nd0=1,nbdirs
      q6pd(nd0, 4) = 2d0*(q6pd(nd0, 2)*q6p(2)+q6p(2)*q6pd(nd0, 2))
    END DO
    q6p(4) = 2d0*q6p(2)*q6p(2) - 1d0
    v = zoe
    DO i=1,152
      v = v + coeff(i)*q1p(ind1(i))*q2p(ind2(i))*q3p(ind3(i))*q4p(ind4(i&
&       ))*q5p(ind5(i))*q6p(ind6(i))
    END DO
    q4pb = 0.0_8
    q1pb = 0.0_8
    q5pb = 0.0_8
    q2pb = 0.0_8
    q6pb = 0.0_8
    q3pb = 0.0_8
    DO nd0=1,nbdirs
      q2pbd(nd0, :) = 0.0_8
      q4pbd(nd0, :) = 0.0_8
      q1pbd(nd0, :) = 0.0_8
      q6pbd(nd0, :) = 0.0_8
      q3pbd(nd0, :) = 0.0_8
      q5pbd(nd0, :) = 0.0_8
    END DO
    DO i=152,1,-1
      temp4 = q3p(ind3(i))*q4p(ind4(i))
      temp3 = q1p(ind1(i))*q2p(ind2(i))
      tempb6 = coeff(i)*q5p(ind5(i))*q6p(ind6(i))*vb
      tempb7 = coeff(i)*temp3*temp4*vb
      DO nd0=1,nbdirs
        temp4d(nd0) = q3pd(nd0, ind3(i))*q4p(ind4(i)) + q3p(ind3(i))*&
&         q4pd(nd0, ind4(i))
        temp3d(nd0) = q1pd(nd0, ind1(i))*q2p(ind2(i)) + q1p(ind1(i))*&
&         q2pd(nd0, ind2(i))
        tempb6d(nd0) = coeff(i)*((q5pd(nd0, ind5(i))*vb+q5p(ind5(i))*vbd&
&         (nd0))*q6p(ind6(i))+q5p(ind5(i))*vb*q6pd(nd0, ind6(i)))
        tempb7d(nd0) = coeff(i)*((temp3d(nd0)*temp4+temp3*temp4d(nd0))*&
&         vb+temp3*temp4*vbd(nd0))
        q1pbd(nd0, ind1(i)) = q1pbd(nd0, ind1(i)) + (temp4d(nd0)*tempb6+&
&         temp4*tempb6d(nd0))*q2p(ind2(i)) + temp4*tempb6*q2pd(nd0, ind2&
&         (i))
        q2pbd(nd0, ind2(i)) = q2pbd(nd0, ind2(i)) + (temp4d(nd0)*tempb6+&
&         temp4*tempb6d(nd0))*q1p(ind1(i)) + temp4*tempb6*q1pd(nd0, ind1&
&         (i))
        q3pbd(nd0, ind3(i)) = q3pbd(nd0, ind3(i)) + (temp3d(nd0)*tempb6+&
&         temp3*tempb6d(nd0))*q4p(ind4(i)) + temp3*tempb6*q4pd(nd0, ind4&
&         (i))
        q4pbd(nd0, ind4(i)) = q4pbd(nd0, ind4(i)) + (temp3d(nd0)*tempb6+&
&         temp3*tempb6d(nd0))*q3p(ind3(i)) + temp3*tempb6*q3pd(nd0, ind3&
&         (i))
        q5pbd(nd0, ind5(i)) = q5pbd(nd0, ind5(i)) + q6pd(nd0, ind6(i))*&
&         tempb7 + q6p(ind6(i))*tempb7d(nd0)
        q6pbd(nd0, ind6(i)) = q6pbd(nd0, ind6(i)) + q5pd(nd0, ind5(i))*&
&         tempb7 + q5p(ind5(i))*tempb7d(nd0)
      END DO
      q1pb(ind1(i)) = q1pb(ind1(i)) + temp4*q2p(ind2(i))*tempb6
      q2pb(ind2(i)) = q2pb(ind2(i)) + temp4*q1p(ind1(i))*tempb6
      q3pb(ind3(i)) = q3pb(ind3(i)) + temp3*q4p(ind4(i))*tempb6
      q4pb(ind4(i)) = q4pb(ind4(i)) + temp3*q3p(ind3(i))*tempb6
      q5pb(ind5(i)) = q5pb(ind5(i)) + q6p(ind6(i))*tempb7
      q6pb(ind6(i)) = q6pb(ind6(i)) + q5p(ind5(i))*tempb7
    END DO
    CALL POPREAL8_DV(q6p(4), q6pd(:, 4), nbdirs)
    DO nd0=1,nbdirs
      q6pbd(nd0, 2) = q6pbd(nd0, 2) + 2d0*2*(q6pd(nd0, 2)*q6pb(4)+q6p(2)&
&       *q6pbd(nd0, 4))
      q6pbd(nd0, 4) = 0.0_8
    END DO
    q6pb(2) = q6pb(2) + 2d0*2*q6p(2)*q6pb(4)
    q6pb(4) = 0.0_8
    CALL POPREAL8_DV(q6p(3), q6pd(:, 3), nbdirs)
    DO nd0=1,nbdirs
      q6pbd(nd0, 1) = q6pbd(nd0, 1) + 2d0*q6pd(nd0, 2)*q6pb(3) + (2d0*&
&       q6p(2)-1d0)*q6pbd(nd0, 3)
    END DO
    q6pb(1) = q6pb(1) + (2d0*q6p(2)-1d0)*q6pb(3)
    DO nd0=1,nbdirs
      q6pbd(nd0, 2) = q6pbd(nd0, 2) + 2d0*(q6pd(nd0, 1)*q6pb(3)+q6p(1)*&
&       q6pbd(nd0, 3))
      q6pbd(nd0, 3) = 0.0_8
    END DO
    q6pb(2) = q6pb(2) + q6p(1)*2d0*q6pb(3)
    q6pb(3) = 0.0_8
    CALL POPREAL8_DV(q6p(2), q6pd(:, 2), nbdirs)
    DO nd0=1,nbdirs
      q6pbd(nd0, 1) = q6pbd(nd0, 1) + 2d0*2*(q6pd(nd0, 1)*q6pb(2)+q6p(1)&
&       *q6pbd(nd0, 2))
      q6pbd(nd0, 2) = 0.0_8
      cosqbd(nd0) = q6pbd(nd0, 1)
    END DO
    q6pb(1) = q6pb(1) + 2d0*2*q6p(1)*q6pb(2)
    q6pb(2) = 0.0_8
    cosqb = q6pb(1)
    q1b = 0.0_8
    q2b = 0.0_8
    q3b = 0.0_8
    q4b = 0.0_8
    q5b = 0.0_8
    DO nd0=1,nbdirs
      q4bd(nd0) = 0.0_8
      q1bd(nd0) = 0.0_8
      q5bd(nd0) = 0.0_8
      q2bd(nd0) = 0.0_8
      q3bd(nd0) = 0.0_8
    END DO
    DO i=4,1,-1
      CALL POPREAL8_DV(q5p(i), q5pd(:, i), nbdirs)
      DO nd0=1,nbdirs
        q5pbd(nd0, i-1) = q5pbd(nd0, i-1) + q5d(nd0)*q5pb(i) + q5*q5pbd(&
&         nd0, i)
        q4pbd(nd0, i-1) = q4pbd(nd0, i-1) + q4d(nd0)*q4pb(i) + q4*q4pbd(&
&         nd0, i)
        q3pbd(nd0, i-1) = q3pbd(nd0, i-1) + q3d(nd0)*q3pb(i) + q3*q3pbd(&
&         nd0, i)
        q2pbd(nd0, i-1) = q2pbd(nd0, i-1) + q2d(nd0)*q2pb(i) + q2*q2pbd(&
&         nd0, i)
        q1pbd(nd0, i-1) = q1pbd(nd0, i-1) + q1d(nd0)*q1pb(i) + q1*q1pbd(&
&         nd0, i)
      END DO
      q5pb(i-1) = q5pb(i-1) + q5*q5pb(i)
      CALL POPREAL8_DV(q4p(i), q4pd(:, i), nbdirs)
      q4pb(i-1) = q4pb(i-1) + q4*q4pb(i)
      CALL POPREAL8_DV(q3p(i), q3pd(:, i), nbdirs)
      q3pb(i-1) = q3pb(i-1) + q3*q3pb(i)
      CALL POPREAL8_DV(q2p(i), q2pd(:, i), nbdirs)
      q2pb(i-1) = q2pb(i-1) + q2*q2pb(i)
      CALL POPREAL8_DV(q1p(i), q1pd(:, i), nbdirs)
      q1pb(i-1) = q1pb(i-1) + q1*q1pb(i)
      DO nd0=1,nbdirs
        q5bd(nd0) = q5bd(nd0) + q5pd(nd0, i-1)*q5pb(i) + q5p(i-1)*q5pbd(&
&         nd0, i)
        q5pbd(nd0, i) = 0.0_8
        q4bd(nd0) = q4bd(nd0) + q4pd(nd0, i-1)*q4pb(i) + q4p(i-1)*q4pbd(&
&         nd0, i)
        q4pbd(nd0, i) = 0.0_8
        q3bd(nd0) = q3bd(nd0) + q3pd(nd0, i-1)*q3pb(i) + q3p(i-1)*q3pbd(&
&         nd0, i)
        q3pbd(nd0, i) = 0.0_8
        q2bd(nd0) = q2bd(nd0) + q2pd(nd0, i-1)*q2pb(i) + q2p(i-1)*q2pbd(&
&         nd0, i)
        q2pbd(nd0, i) = 0.0_8
        q1bd(nd0) = q1bd(nd0) + q1pd(nd0, i-1)*q1pb(i) + q1p(i-1)*q1pbd(&
&         nd0, i)
        q1pbd(nd0, i) = 0.0_8
      END DO
      q5b = q5b + q5p(i-1)*q5pb(i)
      q5pb(i) = 0.0_8
      q4b = q4b + q4p(i-1)*q4pb(i)
      q4pb(i) = 0.0_8
      q3b = q3b + q3p(i-1)*q3pb(i)
      q3pb(i) = 0.0_8
      q2b = q2b + q2p(i-1)*q2pb(i)
      q2pb(i) = 0.0_8
      q1b = q1b + q1p(i-1)*q1pb(i)
      q1pb(i) = 0.0_8
    END DO
    DO nd0=1,nbdirs
      aooh2bd(nd0) = q5bd(nd0)
      ah1oobd(nd0) = q4bd(nd0)
      ro2h2bd(nd0) = (-(ro2h2d(nd0)/ro2h2**2)-(ro2h2d(nd0)*ro2h2**2-(&
&       ro2h2-rm_oh)*2*ro2h2*ro2h2d(nd0))/(ro2h2**2)**2)*q2b + (1.0/&
&       ro2h2-(ro2h2-rm_oh)/ro2h2**2)*q2bd(nd0)
      rh1o1bd(nd0) = (-(rh1o1d(nd0)/rh1o1**2)-(rh1o1d(nd0)*rh1o1**2-(&
&       rh1o1-rm_oh)*2*rh1o1*rh1o1d(nd0))/(rh1o1**2)**2)*q1b + (1.0/&
&       rh1o1-(rh1o1-rm_oh)/rh1o1**2)*q1bd(nd0)
      ro1o2bd(nd0) = (-(ro1o2d(nd0)/ro1o2**2)-(ro1o2d(nd0)*ro1o2**2-(&
&       ro1o2-rm_oo)*2*ro1o2*ro1o2d(nd0))/(ro1o2**2)**2)*q3b + (1.0/&
&       ro1o2-(ro1o2-rm_oo)/ro1o2**2)*q3bd(nd0)
    END DO
    aooh2b = q5b
    ah1oob = q4b
    ro2h2b = (1.0/ro2h2-(ro2h2-rm_oh)/ro2h2**2)*q2b
    rh1o1b = (1.0/rh1o1-(rh1o1-rm_oh)/rh1o1**2)*q1b
    ro1o2b = (1.0/ro1o2-(ro1o2-rm_oo)/ro1o2**2)*q3b
    CALL POPCONTROL1B(branch)
    IF (branch .EQ. 0) THEN
      cosqb = 0.0_8
      DO nd0=1,nbdirs
        cosqbd(nd0) = 0.0_8
      END DO
    END IF
    CALL POPCONTROL1B(branch)
    IF (branch .EQ. 0) THEN
      cosqb = 0.0_8
      DO nd0=1,nbdirs
        cosqbd(nd0) = 0.0_8
      END DO
    END IF
    IF (n1/d1 .EQ. 1.0 .OR. n1/d1 .EQ. -1.0) THEN
      tempb5 = 0.0
      DO nd0=1,nbdirs
        tempb5d(nd0) = 0.0_8
      END DO
    ELSE
      arg1 = 1.0 - (n1/d1)**2
      result1 = SQRT(arg1)
      DO nd0=1,nbdirs
        arg1d(nd0) = -(2*n1*(n1d(nd0)*d1-n1*d1d(nd0))/d1**3)
        IF (arg1 .EQ. 0.0) THEN
          result1d(nd0) = 0.0_8
        ELSE
          result1d(nd0) = arg1d(nd0)/(2.0*SQRT(arg1))
        END IF
        tempb5d(nd0) = -((ah1oobd(nd0)*result1*d1-ah1oob*(result1d(nd0)*&
&         d1+result1*d1d(nd0)))/(result1*d1)**2)
      END DO
      tempb5 = -(ah1oob/(result1*d1))
    END IF
    DO nd0=1,nbdirs
      d1bd(nd0) = -(((n1d(nd0)*tempb5+n1*tempb5d(nd0))*d1-n1*tempb5*d1d(&
&       nd0))/d1**2)
    END DO
    d1b = -(n1*tempb5/d1)
    IF (n2/d2 .EQ. 1.0 .OR. n2/d2 .EQ. -1.0) THEN
      tempb3 = 0.0
      DO nd0=1,nbdirs
        tempb3d(nd0) = 0.0_8
      END DO
    ELSE
      arg1 = 1.0 - (n2/d2)**2
      result1 = SQRT(arg1)
      DO nd0=1,nbdirs
        arg1d(nd0) = -(2*n2*(n2d(nd0)*d2-n2*d2d(nd0))/d2**3)
        IF (arg1 .EQ. 0.0) THEN
          result1d(nd0) = 0.0_8
        ELSE
          result1d(nd0) = arg1d(nd0)/(2.0*SQRT(arg1))
        END IF
        tempb3d(nd0) = -((aooh2bd(nd0)*result1*d2-aooh2b*(result1d(nd0)*&
&         d2+result1*d2d(nd0)))/(result1*d2)**2)
      END DO
      tempb3 = -(aooh2b/(result1*d2))
    END IF
    d2b = -(n2*tempb3/d2)
    DO nd0=1,nbdirs
      n2bd(nd0) = tempb3d(nd0)
      d2bd(nd0) = -(((n2d(nd0)*tempb3+n2*tempb3d(nd0))*d2-n2*tempb3*d2d(&
&       nd0))/d2**2)
      ro1o2bd(nd0) = ro1o2bd(nd0) + rh1o1d(nd0)*d1b + rh1o1*d1bd(nd0) + &
&       ro2h2d(nd0)*d2b + ro2h2*d2bd(nd0)
      n1bd(nd0) = tempb5d(nd0)
      rh1o1bd(nd0) = rh1o1bd(nd0) + ro1o2d(nd0)*d1b + ro1o2*d1bd(nd0)
    END DO
    n2b = tempb3
    ro1o2b = ro1o2b + rh1o1*d1b + ro2h2*d2b
    n1b = tempb5
    rh1o1b = rh1o1b + ro1o2*d1b
    IF (c4**2 + c5**2 + c6**2 .EQ. 0.0) THEN
      tempb1 = 0.0
      DO nd0=1,nbdirs
        tempb1d(nd0) = 0.0_8
      END DO
    ELSE
      arg1 = c4**2 + c5**2 + c6**2
      result1 = SQRT(arg1)
      DO nd0=1,nbdirs
        arg1d(nd0) = 2*c4*c4d(nd0) + 2*c5*c5d(nd0) + 2*c6*c6d(nd0)
        IF (arg1 .EQ. 0.0) THEN
          result1d(nd0) = 0.0_8
        ELSE
          result1d(nd0) = arg1d(nd0)/(2.0*SQRT(arg1))
        END IF
        tempb1d(nd0) = (ro1o2bd(nd0)*2.0*result1-ro1o2b*2.0*result1d(nd0&
&         ))/(2.0*result1)**2
      END DO
      tempb1 = ro1o2b/(2.0*result1)
    END IF
    IF (c1**2 + c2**2 + c3**2 .EQ. 0.0) THEN
      tempb2 = 0.0
      DO nd0=1,nbdirs
        tempb2d(nd0) = 0.0_8
      END DO
    ELSE
      arg1 = c1**2 + c2**2 + c3**2
      result1 = SQRT(arg1)
      DO nd0=1,nbdirs
        arg1d(nd0) = 2*c1*c1d(nd0) + 2*c2*c2d(nd0) + 2*c3*c3d(nd0)
        IF (arg1 .EQ. 0.0) THEN
          result1d(nd0) = 0.0_8
        ELSE
          result1d(nd0) = arg1d(nd0)/(2.0*SQRT(arg1))
        END IF
        tempb2d(nd0) = (rh1o1bd(nd0)*2.0*result1-rh1o1b*2.0*result1d(nd0&
&         ))/(2.0*result1)**2
      END DO
      tempb2 = rh1o1b/(2.0*result1)
    END IF
    temp0 = x_normal2**2 + y_normal2**2 + z_normal2**2
    temp = x_normal1**2 + y_normal1**2 + z_normal1**2
    DO nd0=1,nbdirs
      nbd(nd0) = (cosqbd(nd0)*d-cosqb*dd(nd0))/d**2
      dbd(nd0) = -(((nd(nd0)*cosqb+n*cosqbd(nd0))*d**2-n*cosqb*2*d*dd(&
&       nd0))/(d**2)**2)
      temp0d(nd0) = 2*x_normal2*x_normal2d(nd0) + 2*y_normal2*y_normal2d&
&       (nd0) + 2*z_normal2*z_normal2d(nd0)
      IF (temp0 .EQ. 0.0) THEN
        temp2d(nd0) = 0.0_8
      ELSE
        temp2d(nd0) = temp0d(nd0)/(2.0*SQRT(temp0))
      END IF
      tempd(nd0) = 2*x_normal1*x_normal1d(nd0) + 2*y_normal1*y_normal1d(&
&       nd0) + 2*z_normal1*z_normal1d(nd0)
      IF (temp .EQ. 0.0) THEN
        temp1d(nd0) = 0.0_8
      ELSE
        temp1d(nd0) = tempd(nd0)/(2.0*SQRT(temp))
      END IF
    END DO
    nb = cosqb/d
    db = -(n*cosqb/d**2)
    temp2 = SQRT(temp0)
    temp1 = SQRT(temp)
    IF (temp .EQ. 0.0) THEN
      tempb = 0.0
      DO nd0=1,nbdirs
        tempbd(nd0) = 0.0_8
      END DO
    ELSE
      DO nd0=1,nbdirs
        tempbd(nd0) = ((temp2d(nd0)*db+temp2*dbd(nd0))*2.0*temp1-temp2*&
&         db*2.0*temp1d(nd0))/(2.0*temp1)**2
      END DO
      tempb = temp2*db/(2.0*temp1)
    END IF
    IF (temp0 .EQ. 0.0) THEN
      tempb0 = 0.0
      DO nd0=1,nbdirs
        tempb0d(nd0) = 0.0_8
      END DO
    ELSE
      DO nd0=1,nbdirs
        tempb0d(nd0) = ((temp1d(nd0)*db+temp1*dbd(nd0))*2.0*temp2-temp1*&
&         db*2.0*temp2d(nd0))/(2.0*temp2)**2
      END DO
      tempb0 = temp1*db/(2.0*temp2)
    END IF
    x_normal1b = x_normal2*nb + 2*x_normal1*tempb
    y_normal1b = y_normal2*nb + 2*y_normal1*tempb
    z_normal1b = z_normal2*nb + 2*z_normal1*tempb
    x_normal2b = x_normal1*nb + 2*x_normal2*tempb0
    y_normal2b = y_normal1*nb + 2*y_normal2*tempb0
    z_normal2b = z_normal1*nb + 2*z_normal2*tempb0
    DO nd0=1,nbdirs
      x_normal1bd(nd0) = x_normal2d(nd0)*nb + x_normal2*nbd(nd0) + 2*(&
&       x_normal1d(nd0)*tempb) + 2*(x_normal1*tempbd(nd0))
      y_normal1bd(nd0) = y_normal2d(nd0)*nb + y_normal2*nbd(nd0) + 2*(&
&       y_normal1d(nd0)*tempb) + 2*(y_normal1*tempbd(nd0))
      z_normal1bd(nd0) = z_normal2d(nd0)*nb + z_normal2*nbd(nd0) + 2*(&
&       z_normal1d(nd0)*tempb) + 2*(z_normal1*tempbd(nd0))
      x_normal2bd(nd0) = x_normal1d(nd0)*nb + x_normal1*nbd(nd0) + 2*(&
&       x_normal2d(nd0)*tempb0) + 2*(x_normal2*tempb0d(nd0))
      y_normal2bd(nd0) = y_normal1d(nd0)*nb + y_normal1*nbd(nd0) + 2*(&
&       y_normal2d(nd0)*tempb0) + 2*(y_normal2*tempb0d(nd0))
      z_normal2bd(nd0) = z_normal1d(nd0)*nb + z_normal1*nbd(nd0) + 2*(&
&       z_normal2d(nd0)*tempb0) + 2*(z_normal2*tempb0d(nd0))
      xcomp3bd(nd0) = ycomp4d(nd0)*z_normal2b + ycomp4*z_normal2bd(nd0) &
&       - zcomp4d(nd0)*y_normal2b - zcomp4*y_normal2bd(nd0)
      ycomp4bd(nd0) = xcomp3d(nd0)*z_normal2b + xcomp3*z_normal2bd(nd0) &
&       - zcomp3d(nd0)*x_normal2b - zcomp3*x_normal2bd(nd0)
      ycomp3bd(nd0) = zcomp4d(nd0)*x_normal2b + zcomp4*x_normal2bd(nd0) &
&       - xcomp4d(nd0)*z_normal2b - xcomp4*z_normal2bd(nd0)
      xcomp4bd(nd0) = zcomp3d(nd0)*y_normal2b + zcomp3*y_normal2bd(nd0) &
&       - ycomp3d(nd0)*z_normal2b - ycomp3*z_normal2bd(nd0)
      zcomp3bd(nd0) = xcomp4d(nd0)*y_normal2b + xcomp4*y_normal2bd(nd0) &
&       - ycomp4d(nd0)*x_normal2b - ycomp4*x_normal2bd(nd0)
      zcomp4bd(nd0) = ycomp3d(nd0)*x_normal2b + ycomp3*x_normal2bd(nd0) &
&       - xcomp3d(nd0)*y_normal2b - xcomp3*y_normal2bd(nd0)
      c15bd(nd0) = zcomp4bd(nd0)
      c14bd(nd0) = ycomp4bd(nd0)
      c13bd(nd0) = xcomp4bd(nd0)
      c6bd(nd0) = 2*(c6d(nd0)*tempb1) + 2*(c6*tempb1d(nd0)) - c9d(nd0)*&
&       n2b - c9*n2bd(nd0) - c3d(nd0)*n1b - c3*n1bd(nd0) - zcomp3bd(nd0)
      c5bd(nd0) = 2*(c5d(nd0)*tempb1) + 2*(c5*tempb1d(nd0)) - c8d(nd0)*&
&       n2b - c8*n2bd(nd0) - c2d(nd0)*n1b - c2*n1bd(nd0) - ycomp3bd(nd0)
      c4bd(nd0) = 2*(c4d(nd0)*tempb1) + 2*(c4*tempb1d(nd0)) - c7d(nd0)*&
&       n2b - c7*n2bd(nd0) - c1d(nd0)*n1b - c1*n1bd(nd0) - xcomp3bd(nd0)
      xcomp1bd(nd0) = ycomp2d(nd0)*z_normal1b + ycomp2*z_normal1bd(nd0) &
&       - zcomp2d(nd0)*y_normal1b - zcomp2*y_normal1bd(nd0)
      ycomp2bd(nd0) = xcomp1d(nd0)*z_normal1b + xcomp1*z_normal1bd(nd0) &
&       - zcomp1d(nd0)*x_normal1b - zcomp1*x_normal1bd(nd0)
      ycomp1bd(nd0) = zcomp2d(nd0)*x_normal1b + zcomp2*x_normal1bd(nd0) &
&       - xcomp2d(nd0)*z_normal1b - xcomp2*z_normal1bd(nd0)
      xcomp2bd(nd0) = zcomp1d(nd0)*y_normal1b + zcomp1*y_normal1bd(nd0) &
&       - ycomp1d(nd0)*z_normal1b - ycomp1*z_normal1bd(nd0)
      zcomp1bd(nd0) = xcomp2d(nd0)*y_normal1b + xcomp2*y_normal1bd(nd0) &
&       - ycomp2d(nd0)*x_normal1b - ycomp2*x_normal1bd(nd0)
      zcomp2bd(nd0) = ycomp1d(nd0)*x_normal1b + ycomp1*x_normal1bd(nd0) &
&       - xcomp1d(nd0)*y_normal1b - xcomp1*y_normal1bd(nd0)
      c12bd(nd0) = zcomp2bd(nd0)
      c11bd(nd0) = ycomp2bd(nd0)
      c10bd(nd0) = xcomp2bd(nd0)
      c3bd(nd0) = 2*(c3d(nd0)*tempb2) + 2*(c3*tempb2d(nd0)) - c6d(nd0)*&
&       n1b - c6*n1bd(nd0) - zcomp1bd(nd0)
      c2bd(nd0) = 2*(c2d(nd0)*tempb2) + 2*(c2*tempb2d(nd0)) - c5d(nd0)*&
&       n1b - c5*n1bd(nd0) - ycomp1bd(nd0)
      c1bd(nd0) = 2*(c1d(nd0)*tempb2) + 2*(c1*tempb2d(nd0)) - c4d(nd0)*&
&       n1b - c4*n1bd(nd0) - xcomp1bd(nd0)
      ro2h2bd(nd0) = ro2h2bd(nd0) + ro1o2d(nd0)*d2b + ro1o2*d2bd(nd0)
    END DO
    xcomp3b = ycomp4*z_normal2b - zcomp4*y_normal2b
    ycomp4b = xcomp3*z_normal2b - zcomp3*x_normal2b
    ycomp3b = zcomp4*x_normal2b - xcomp4*z_normal2b
    xcomp4b = zcomp3*y_normal2b - ycomp3*z_normal2b
    zcomp3b = xcomp4*y_normal2b - ycomp4*x_normal2b
    zcomp4b = ycomp3*x_normal2b - xcomp3*y_normal2b
    c15b = zcomp4b
    c14b = ycomp4b
    c13b = xcomp4b
    c6b = 2*c6*tempb1 - c9*n2b - c3*n1b - zcomp3b
    c5b = 2*c5*tempb1 - c8*n2b - c2*n1b - ycomp3b
    c4b = 2*c4*tempb1 - c7*n2b - c1*n1b - xcomp3b
    xcomp1b = ycomp2*z_normal1b - zcomp2*y_normal1b
    ycomp2b = xcomp1*z_normal1b - zcomp1*x_normal1b
    ycomp1b = zcomp2*x_normal1b - xcomp2*z_normal1b
    xcomp2b = zcomp1*y_normal1b - ycomp1*z_normal1b
    zcomp1b = xcomp2*y_normal1b - ycomp2*x_normal1b
    zcomp2b = ycomp1*x_normal1b - xcomp1*y_normal1b
    c12b = zcomp2b
    c11b = ycomp2b
    c10b = xcomp2b
    c3b = 2*c3*tempb2 - c6*n1b - zcomp1b
    c2b = 2*c2*tempb2 - c5*n1b - ycomp1b
    c1b = 2*c1*tempb2 - c4*n1b - xcomp1b
    ro2h2b = ro2h2b + ro1o2*d2b
    IF (c7**2 + c8**2 + c9**2 .EQ. 0.0) THEN
      tempb4 = 0.0
      DO nd0=1,nbdirs
        tempb4d(nd0) = 0.0_8
      END DO
    ELSE
      arg1 = c7**2 + c8**2 + c9**2
      result1 = SQRT(arg1)
      DO nd0=1,nbdirs
        arg1d(nd0) = 2*c7*c7d(nd0) + 2*c8*c8d(nd0) + 2*c9*c9d(nd0)
        IF (arg1 .EQ. 0.0) THEN
          result1d(nd0) = 0.0_8
        ELSE
          result1d(nd0) = arg1d(nd0)/(2.0*SQRT(arg1))
        END IF
        tempb4d(nd0) = (ro2h2bd(nd0)*2.0*result1-ro2h2b*2.0*result1d(nd0&
&         ))/(2.0*result1)**2
      END DO
      tempb4 = ro2h2b/(2.0*result1)
    END IF
    DO nd0=1,nbdirs
      c7bd(nd0) = 2*(c7d(nd0)*tempb4) + 2*(c7*tempb4d(nd0)) - c4d(nd0)*&
&       n2b - c4*n2bd(nd0)
      c8bd(nd0) = 2*(c8d(nd0)*tempb4) + 2*(c8*tempb4d(nd0)) - c5d(nd0)*&
&       n2b - c5*n2bd(nd0)
      c9bd(nd0) = 2*(c9d(nd0)*tempb4) + 2*(c9*tempb4d(nd0)) - c6d(nd0)*&
&       n2b - c6*n2bd(nd0)
      xbd(nd0, :) = 0.0_8
      xbd(nd0, 6) = c15bd(nd0)
      xbd(nd0, 12) = xbd(nd0, 12) - c15bd(nd0)
      xbd(nd0, 5) = xbd(nd0, 5) + c14bd(nd0)
      xbd(nd0, 11) = xbd(nd0, 11) - c14bd(nd0)
      xbd(nd0, 4) = xbd(nd0, 4) + c13bd(nd0)
      xbd(nd0, 10) = xbd(nd0, 10) - c13bd(nd0)
      xbd(nd0, 3) = xbd(nd0, 3) + c12bd(nd0)
      xbd(nd0, 9) = xbd(nd0, 9) - c12bd(nd0)
      xbd(nd0, 2) = xbd(nd0, 2) + c11bd(nd0)
      xbd(nd0, 8) = xbd(nd0, 8) - c11bd(nd0)
      xbd(nd0, 1) = xbd(nd0, 1) + c10bd(nd0)
      xbd(nd0, 7) = xbd(nd0, 7) - c10bd(nd0)
      xbd(nd0, 9) = xbd(nd0, 9) + c9bd(nd0)
      xbd(nd0, 12) = xbd(nd0, 12) - c9bd(nd0)
      xbd(nd0, 8) = xbd(nd0, 8) + c8bd(nd0)
      xbd(nd0, 11) = xbd(nd0, 11) - c8bd(nd0)
      xbd(nd0, 7) = xbd(nd0, 7) + c7bd(nd0)
      xbd(nd0, 10) = xbd(nd0, 10) - c7bd(nd0)
      xbd(nd0, 6) = xbd(nd0, 6) + c6bd(nd0)
      xbd(nd0, 9) = xbd(nd0, 9) - c6bd(nd0)
      xbd(nd0, 5) = xbd(nd0, 5) + c5bd(nd0)
      xbd(nd0, 8) = xbd(nd0, 8) - c5bd(nd0)
      xbd(nd0, 4) = xbd(nd0, 4) + c4bd(nd0)
      xbd(nd0, 7) = xbd(nd0, 7) - c4bd(nd0)
      xbd(nd0, 3) = xbd(nd0, 3) + c3bd(nd0)
      xbd(nd0, 6) = xbd(nd0, 6) - c3bd(nd0)
      xbd(nd0, 2) = xbd(nd0, 2) + c2bd(nd0)
      xbd(nd0, 5) = xbd(nd0, 5) - c2bd(nd0)
      xbd(nd0, 1) = xbd(nd0, 1) + c1bd(nd0)
      xbd(nd0, 4) = xbd(nd0, 4) - c1bd(nd0)
    END DO
    c7b = 2*c7*tempb4 - c4*n2b
    c8b = 2*c8*tempb4 - c5*n2b
    c9b = 2*c9*tempb4 - c6*n2b
    xb = 0.0_8
    xb(6) = xb(6) + c15b
    xb(12) = xb(12) - c15b
    xb(5) = xb(5) + c14b
    xb(11) = xb(11) - c14b
    xb(4) = xb(4) + c13b
    xb(10) = xb(10) - c13b
    xb(3) = xb(3) + c12b
    xb(9) = xb(9) - c12b
    xb(2) = xb(2) + c11b
    xb(8) = xb(8) - c11b
    xb(1) = xb(1) + c10b
    xb(7) = xb(7) - c10b
    xb(9) = xb(9) + c9b
    xb(12) = xb(12) - c9b
    xb(8) = xb(8) + c8b
    xb(11) = xb(11) - c8b
    xb(7) = xb(7) + c7b
    xb(10) = xb(10) - c7b
    xb(6) = xb(6) + c6b
    xb(9) = xb(9) - c6b
    xb(5) = xb(5) + c5b
    xb(8) = xb(8) - c5b
    xb(4) = xb(4) + c4b
    xb(7) = xb(7) - c4b
    xb(3) = xb(3) + c3b
    xb(6) = xb(6) - c3b
    xb(2) = xb(2) + c2b
    xb(5) = xb(5) - c2b
    xb(1) = xb(1) + c1b
    xb(4) = xb(4) - c1b
    vb = 0.0_8
    DO nd0=1,nbdirs
      vbd(nd0) = 0.0_8
    END DO
  END SUBROUTINE SURF_B_DV
!  Differentiation of surf in reverse (adjoint) mode (with options i4 dr8 r4):
!   gradient     of useful results: v
!   with respect to varying inputs: v x
!   RW status of diff variables: v:in-zero x:out
!..................................
!@the unit of input: x is Angstrom
!the unit of output:
!@ pot: hartree 
!@ dv: hartee/A
!@ ddv: hartree/A^2
  SUBROUTINE SURF_B(x, xb, v, vb) bind(c, name="pes_h2o2_surf_b")
    IMPLICIT NONE
    REAL*8 :: v, x(nx)
    REAL*8 :: vb, xb(nx)
    INTEGER :: i
!integer,parameter::nhes=nx*(nx+1)/2
!integer :: i,j
!integer,parameter::row(nhes) =(/ ( (i,i=j,nx),j=1,nx) /)
!integer,parameter::col(nhes) =(/ ( (j,i=j,nx),j=1,nx) /)
!real(8) ::ddv(nhes)
    REAL*8 :: q1p(0:4), q2p(0:4), q3p(0:4), q4p(0:4), q5p(0:4), q6p(0:4)
    REAL*8 :: q1pb(0:4), q2pb(0:4), q3pb(0:4), q4pb(0:4), q5pb(0:4), &
&   q6pb(0:4)
    REAL*8 :: n, n1, n2
    REAL*8 :: nb, n1b, n2b
    REAL*8 :: rh1o1, ro1o2, ro2h2
    REAL*8 :: rh1o1b, ro1o2b, ro2h2b
    REAL*8 :: d1, d2, d, ah1oo, aooh2, thooh
    REAL*8 :: d1b, d2b, db, ah1oob, aooh2b
    REAL*8 :: xcomp1, ycomp1, zcomp1
    REAL*8 :: xcomp1b, ycomp1b, zcomp1b
    REAL*8 :: xcomp2, ycomp2, zcomp2
    REAL*8 :: xcomp2b, ycomp2b, zcomp2b
    REAL*8 :: xcomp3, ycomp3, zcomp3
    REAL*8 :: xcomp3b, ycomp3b, zcomp3b
    REAL*8 :: xcomp4, ycomp4, zcomp4
    REAL*8 :: xcomp4b, ycomp4b, zcomp4b
    REAL*8 :: x_normal1, y_normal1, z_normal1
    REAL*8 :: x_normal1b, y_normal1b, z_normal1b
    REAL*8 :: x_normal2, y_normal2, z_normal2
    REAL*8 :: x_normal2b, y_normal2b, z_normal2b
    REAL*8 :: q1, q2, q3, q4, q5, q6
    REAL*8 :: q1b, q2b, q3b, q4b, q5b
!real(8)::vH1O1(3),vO1O2(3),vO2H2(3),vH1O2(3),vO1H2(3),vH1H2(3)
    REAL*8 :: c1, c2, c3, c4, c5, c6, c7, c8, c9, c10
    REAL*8 :: c1b, c2b, c3b, c4b, c5b, c6b, c7b, c8b, c9b, c10b
    REAL*8 :: c11, c12, c13, c14, c15
    REAL*8 :: c11b, c12b, c13b, c14b, c15b
    REAL*8 :: cost
    INTRINSIC SQRT
    INTRINSIC ACOS
    INTEGER :: branch
    REAL*8 :: temp3
    REAL*8 :: temp2
    REAL*8 :: temp1
    REAL*8 :: temp0
    REAL*8 :: cosqb
    REAL*8 :: tempb7
    REAL*8 :: tempb6
    REAL*8 :: tempb5
    REAL*8 :: tempb4
    REAL*8 :: tempb3
    REAL*8 :: tempb2
    REAL*8 :: tempb1
    REAL*8 :: tempb0
    REAL*8 :: cosq
    REAL*8 :: tempb
    REAL*8 :: temp
    REAL*8 :: temp4
    EXTERNAL PUSHCONTROL1B
    EXTERNAL PUSHREAL8
    EXTERNAL POPREAL8
    EXTERNAL POPCONTROL1B
    REAL*8 :: arg1
    REAL*8 :: result1
    REAL*8 :: arg2
    REAL*8 :: result2
! vector
    c1 = x(1) - x(4)
    c2 = x(2) - x(5)
    c3 = x(3) - x(6)
    c4 = x(4) - x(7)
    c5 = x(5) - x(8)
    c6 = x(6) - x(9)
    c7 = x(7) - x(10)
    c8 = x(8) - x(11)
    c9 = x(9) - x(12)
    c10 = x(1) - x(7)
    c11 = x(2) - x(8)
    c12 = x(3) - x(9)
    c13 = x(4) - x(10)
    c14 = x(5) - x(11)
    c15 = x(6) - x(12)
!c16=x(1)-x(10)
!c17=x(2)-x(11)
!c18=x(3)-x(12)
!
! H1 -- O1 -- O2 -- H2
!   rH1O1 rO1O2 rO2H2
! 
!  angle H1O1O2 = AH1OO
!  angle O1O2H2 = AOOH2
!
!  TORSION HOOH = THOOH
    arg1 = c1**2 + c2**2 + c3**2
    rh1o1 = SQRT(arg1)
    arg1 = c4**2 + c5**2 + c6**2
    ro1o2 = SQRT(arg1)
    arg1 = c7**2 + c8**2 + c9**2
    ro2h2 = SQRT(arg1)
! The potential can give weird values for unusual geometries
! replace with some high value in these unphysical regions and
! then exit
!
    n1 = -(c4*c1+c5*c2+c6*c3)
    d1 = ro1o2*rh1o1
    arg1 = n1/d1
    ah1oo = ACOS(arg1)
    n2 = -(c7*c4+c8*c5+c9*c6)
    d2 = ro2h2*ro1o2
    arg1 = n2/d2
    aooh2 = ACOS(arg1)
! Calculate torsion angle HOOH
! X(4) - X(1)
    xcomp1 = -c1
! X(5) - X(2)
    ycomp1 = -c2
! X(6) - X(3)
    zcomp1 = -c3
    xcomp2 = c10
    ycomp2 = c11
    zcomp2 = c12
    x_normal1 = ycomp1*zcomp2 - zcomp1*ycomp2
    y_normal1 = zcomp1*xcomp2 - xcomp1*zcomp2
    z_normal1 = xcomp1*ycomp2 - ycomp1*xcomp2
! X(7) - X(4) 
    xcomp3 = -c4
! X(8) - X(5) 
    ycomp3 = -c5
! X(9) - X(6)
    zcomp3 = -c6
    xcomp4 = c13
    ycomp4 = c14
    zcomp4 = c15
    x_normal2 = ycomp3*zcomp4 - zcomp3*ycomp4
    y_normal2 = zcomp3*xcomp4 - xcomp3*zcomp4
    z_normal2 = xcomp3*ycomp4 - ycomp3*xcomp4
    n = x_normal1*x_normal2 + y_normal1*y_normal2 + z_normal1*z_normal2
    arg1 = x_normal1*x_normal1 + y_normal1*y_normal1 + z_normal1*&
&     z_normal1
    result1 = SQRT(arg1)
    arg2 = x_normal2*x_normal2 + y_normal2*y_normal2 + z_normal2*&
&     z_normal2
    result2 = SQRT(arg2)
    d = result1*result2
    cosq = n/d
    IF (cosq .GT. 1d0) THEN
      cosq = 1d0
      CALL PUSHCONTROL1B(0)
    ELSE
      CALL PUSHCONTROL1B(1)
    END IF
    IF (cosq .LT. -1d0) THEN
      cosq = -1d0
      CALL PUSHCONTROL1B(0)
    ELSE
      CALL PUSHCONTROL1B(1)
    END IF
! in radians
!R1 =  RH1O1              
!R2 =  RO1O2             
!R3 =  RO2H2         
!A1 =  AH1OO          
!A2 =  AOOH2              
!Q6 =  THOOH  
! Q1,Q2, and Q3 represent the stretching modes
! Q4 and Q5  are the bending modes
! Q6 is the torsional mode 
! Q1, Q2, Q3 are dimensionless, Q4, Q5, and Q6 are in radians
    q3 = (ro1o2-rm_oo)/ro1o2
    q1 = (rh1o1-rm_oh)/rh1o1
    q2 = (ro2h2-rm_oh)/ro2h2
    q4 = ah1oo - angle_ooh
    q5 = aooh2 - angle_ooh
    q1p(0) = 1.d0
    q2p(0) = 1.d0
    q3p(0) = 1.d0
    q4p(0) = 1.d0
    q5p(0) = 1.d0
    q6p(0) = 1.d0
    DO i=1,4
! q1**i
      CALL PUSHREAL8(q1p(i))
      q1p(i) = q1p(i-1)*q1
! q2**i
      CALL PUSHREAL8(q2p(i))
      q2p(i) = q2p(i-1)*q2
! q3**i
      CALL PUSHREAL8(q3p(i))
      q3p(i) = q3p(i-1)*q3
! q4**i
      CALL PUSHREAL8(q4p(i))
      q4p(i) = q4p(i-1)*q4
! q5**i
      CALL PUSHREAL8(q5p(i))
      q5p(i) = q5p(i-1)*q5
    END DO
! cos(q6) 
    q6p(1) = cosq
! cos2q
    CALL PUSHREAL8(q6p(2))
    q6p(2) = 2d0*q6p(1)*q6p(1) - 1d0
! cos3q
    CALL PUSHREAL8(q6p(3))
    q6p(3) = q6p(1)*(2d0*q6p(2)-1d0)
! cos4q
    CALL PUSHREAL8(q6p(4))
    q6p(4) = 2d0*q6p(2)*q6p(2) - 1d0
    v = zoe
    DO i=1,152
      v = v + coeff(i)*q1p(ind1(i))*q2p(ind2(i))*q3p(ind3(i))*q4p(ind4(i&
&       ))*q5p(ind5(i))*q6p(ind6(i))
    END DO
    q4pb = 0.0_8
    q1pb = 0.0_8
    q5pb = 0.0_8
    q2pb = 0.0_8
    q6pb = 0.0_8
    q3pb = 0.0_8
    DO i=152,1,-1
      temp4 = q3p(ind3(i))*q4p(ind4(i))
      temp3 = q1p(ind1(i))*q2p(ind2(i))
      tempb6 = coeff(i)*q5p(ind5(i))*q6p(ind6(i))*vb
      tempb7 = coeff(i)*temp3*temp4*vb
      q1pb(ind1(i)) = q1pb(ind1(i)) + temp4*q2p(ind2(i))*tempb6
      q2pb(ind2(i)) = q2pb(ind2(i)) + temp4*q1p(ind1(i))*tempb6
      q3pb(ind3(i)) = q3pb(ind3(i)) + temp3*q4p(ind4(i))*tempb6
      q4pb(ind4(i)) = q4pb(ind4(i)) + temp3*q3p(ind3(i))*tempb6
      q5pb(ind5(i)) = q5pb(ind5(i)) + q6p(ind6(i))*tempb7
      q6pb(ind6(i)) = q6pb(ind6(i)) + q5p(ind5(i))*tempb7
    END DO
    CALL POPREAL8(q6p(4))
    q6pb(2) = q6pb(2) + 2d0*2*q6p(2)*q6pb(4)
    q6pb(4) = 0.0_8
    CALL POPREAL8(q6p(3))
    q6pb(1) = q6pb(1) + (2d0*q6p(2)-1d0)*q6pb(3)
    q6pb(2) = q6pb(2) + q6p(1)*2d0*q6pb(3)
    q6pb(3) = 0.0_8
    CALL POPREAL8(q6p(2))
    q6pb(1) = q6pb(1) + 2d0*2*q6p(1)*q6pb(2)
    q6pb(2) = 0.0_8
    cosqb = q6pb(1)
    q1b = 0.0_8
    q2b = 0.0_8
    q3b = 0.0_8
    q4b = 0.0_8
    q5b = 0.0_8
    DO i=4,1,-1
      CALL POPREAL8(q5p(i))
      q5pb(i-1) = q5pb(i-1) + q5*q5pb(i)
      q5b = q5b + q5p(i-1)*q5pb(i)
      q5pb(i) = 0.0_8
      CALL POPREAL8(q4p(i))
      q4pb(i-1) = q4pb(i-1) + q4*q4pb(i)
      q4b = q4b + q4p(i-1)*q4pb(i)
      q4pb(i) = 0.0_8
      CALL POPREAL8(q3p(i))
      q3pb(i-1) = q3pb(i-1) + q3*q3pb(i)
      q3b = q3b + q3p(i-1)*q3pb(i)
      q3pb(i) = 0.0_8
      CALL POPREAL8(q2p(i))
      q2pb(i-1) = q2pb(i-1) + q2*q2pb(i)
      q2b = q2b + q2p(i-1)*q2pb(i)
      q2pb(i) = 0.0_8
      CALL POPREAL8(q1p(i))
      q1pb(i-1) = q1pb(i-1) + q1*q1pb(i)
      q1b = q1b + q1p(i-1)*q1pb(i)
      q1pb(i) = 0.0_8
    END DO
    aooh2b = q5b
    ah1oob = q4b
    ro2h2b = (1.0/ro2h2-(ro2h2-rm_oh)/ro2h2**2)*q2b
    rh1o1b = (1.0/rh1o1-(rh1o1-rm_oh)/rh1o1**2)*q1b
    ro1o2b = (1.0/ro1o2-(ro1o2-rm_oo)/ro1o2**2)*q3b
    CALL POPCONTROL1B(branch)
    IF (branch .EQ. 0) cosqb = 0.0_8
    CALL POPCONTROL1B(branch)
    IF (branch .EQ. 0) cosqb = 0.0_8
    IF (n1/d1 .EQ. 1.0 .OR. n1/d1 .EQ. -1.0) THEN
      tempb5 = 0.0
    ELSE
      arg1 = 1.0 - (n1/d1)**2
      result1 = SQRT(arg1)
      tempb5 = -(ah1oob/(result1*d1))
    END IF
    d1b = -(n1*tempb5/d1)
    IF (n2/d2 .EQ. 1.0 .OR. n2/d2 .EQ. -1.0) THEN
      tempb3 = 0.0
    ELSE
      arg1 = 1.0 - (n2/d2)**2
      result1 = SQRT(arg1)
      tempb3 = -(aooh2b/(result1*d2))
    END IF
    n2b = tempb3
    d2b = -(n2*tempb3/d2)
    ro1o2b = ro1o2b + rh1o1*d1b + ro2h2*d2b
    n1b = tempb5
    rh1o1b = rh1o1b + ro1o2*d1b
    IF (c4**2 + c5**2 + c6**2 .EQ. 0.0) THEN
      tempb1 = 0.0
    ELSE
      arg1 = c4**2 + c5**2 + c6**2
      result1 = SQRT(arg1)
      tempb1 = ro1o2b/(2.0*result1)
    END IF
    IF (c1**2 + c2**2 + c3**2 .EQ. 0.0) THEN
      tempb2 = 0.0
    ELSE
      arg1 = c1**2 + c2**2 + c3**2
      result1 = SQRT(arg1)
      tempb2 = rh1o1b/(2.0*result1)
    END IF
    nb = cosqb/d
    db = -(n*cosqb/d**2)
    temp0 = x_normal2**2 + y_normal2**2 + z_normal2**2
    temp2 = SQRT(temp0)
    temp = x_normal1**2 + y_normal1**2 + z_normal1**2
    temp1 = SQRT(temp)
    IF (temp .EQ. 0.0) THEN
      tempb = 0.0
    ELSE
      tempb = temp2*db/(2.0*temp1)
    END IF
    IF (temp0 .EQ. 0.0) THEN
      tempb0 = 0.0
    ELSE
      tempb0 = temp1*db/(2.0*temp2)
    END IF
    x_normal1b = x_normal2*nb + 2*x_normal1*tempb
    y_normal1b = y_normal2*nb + 2*y_normal1*tempb
    z_normal1b = z_normal2*nb + 2*z_normal1*tempb
    x_normal2b = x_normal1*nb + 2*x_normal2*tempb0
    y_normal2b = y_normal1*nb + 2*y_normal2*tempb0
    z_normal2b = z_normal1*nb + 2*z_normal2*tempb0
    xcomp3b = ycomp4*z_normal2b - zcomp4*y_normal2b
    ycomp4b = xcomp3*z_normal2b - zcomp3*x_normal2b
    ycomp3b = zcomp4*x_normal2b - xcomp4*z_normal2b
    xcomp4b = zcomp3*y_normal2b - ycomp3*z_normal2b
    zcomp3b = xcomp4*y_normal2b - ycomp4*x_normal2b
    zcomp4b = ycomp3*x_normal2b - xcomp3*y_normal2b
    c15b = zcomp4b
    c14b = ycomp4b
    c13b = xcomp4b
    c6b = 2*c6*tempb1 - c9*n2b - c3*n1b - zcomp3b
    c5b = 2*c5*tempb1 - c8*n2b - c2*n1b - ycomp3b
    c4b = 2*c4*tempb1 - c7*n2b - c1*n1b - xcomp3b
    xcomp1b = ycomp2*z_normal1b - zcomp2*y_normal1b
    ycomp2b = xcomp1*z_normal1b - zcomp1*x_normal1b
    ycomp1b = zcomp2*x_normal1b - xcomp2*z_normal1b
    xcomp2b = zcomp1*y_normal1b - ycomp1*z_normal1b
    zcomp1b = xcomp2*y_normal1b - ycomp2*x_normal1b
    zcomp2b = ycomp1*x_normal1b - xcomp1*y_normal1b
    c12b = zcomp2b
    c11b = ycomp2b
    c10b = xcomp2b
    c3b = 2*c3*tempb2 - c6*n1b - zcomp1b
    c2b = 2*c2*tempb2 - c5*n1b - ycomp1b
    c1b = 2*c1*tempb2 - c4*n1b - xcomp1b
    ro2h2b = ro2h2b + ro1o2*d2b
    IF (c7**2 + c8**2 + c9**2 .EQ. 0.0) THEN
      tempb4 = 0.0
    ELSE
      arg1 = c7**2 + c8**2 + c9**2
      result1 = SQRT(arg1)
      tempb4 = ro2h2b/(2.0*result1)
    END IF
    c7b = 2*c7*tempb4 - c4*n2b
    c8b = 2*c8*tempb4 - c5*n2b
    c9b = 2*c9*tempb4 - c6*n2b
    xb = 0.0_8
    xb(6) = xb(6) + c15b
    xb(12) = xb(12) - c15b
    xb(5) = xb(5) + c14b
    xb(11) = xb(11) - c14b
    xb(4) = xb(4) + c13b
    xb(10) = xb(10) - c13b
    xb(3) = xb(3) + c12b
    xb(9) = xb(9) - c12b
    xb(2) = xb(2) + c11b
    xb(8) = xb(8) - c11b
    xb(1) = xb(1) + c10b
    xb(7) = xb(7) - c10b
    xb(9) = xb(9) + c9b
    xb(12) = xb(12) - c9b
    xb(8) = xb(8) + c8b
    xb(11) = xb(11) - c8b
    xb(7) = xb(7) + c7b
    xb(10) = xb(10) - c7b
    xb(6) = xb(6) + c6b
    xb(9) = xb(9) - c6b
    xb(5) = xb(5) + c5b
    xb(8) = xb(8) - c5b
    xb(4) = xb(4) + c4b
    xb(7) = xb(7) - c4b
    xb(3) = xb(3) + c3b
    xb(6) = xb(6) - c3b
    xb(2) = xb(2) + c2b
    xb(5) = xb(5) - c2b
    xb(1) = xb(1) + c1b
    xb(4) = xb(4) - c1b
    vb = 0.0_8
  END SUBROUTINE SURF_B
!..................................
!@the unit of input: x is Angstrom
!the unit of output:
!@ pot: hartree 
!@ dv: hartee/A
!@ ddv: hartree/A^2
  SUBROUTINE SURF(x, v) bind(c, name="pes_h2o2_surf")
    IMPLICIT NONE
    REAL*8 :: v, x(nx)
    INTEGER :: i
!integer,parameter::nhes=nx*(nx+1)/2
!integer :: i,j
!integer,parameter::row(nhes) =(/ ( (i,i=j,nx),j=1,nx) /)
!integer,parameter::col(nhes) =(/ ( (j,i=j,nx),j=1,nx) /)
!real(8) ::ddv(nhes)
    REAL*8 :: q1p(0:4), q2p(0:4), q3p(0:4), q4p(0:4), q5p(0:4), q6p(0:4)
    REAL*8 :: n, n1, n2
    REAL*8 :: rh1o1, ro1o2, ro2h2
    REAL*8 :: d1, d2, d, ah1oo, aooh2, thooh
    REAL*8 :: xcomp1, ycomp1, zcomp1
    REAL*8 :: xcomp2, ycomp2, zcomp2
    REAL*8 :: xcomp3, ycomp3, zcomp3
    REAL*8 :: xcomp4, ycomp4, zcomp4
    REAL*8 :: x_normal1, y_normal1, z_normal1
    REAL*8 :: x_normal2, y_normal2, z_normal2
    REAL*8 :: q1, q2, q3, q4, q5, q6
!real(8)::vH1O1(3),vO1O2(3),vO2H2(3),vH1O2(3),vO1H2(3),vH1H2(3)
    REAL*8 :: c1, c2, c3, c4, c5, c6, c7, c8, c9, c10
    REAL*8 :: c11, c12, c13, c14, c15
    REAL*8 :: cost
    INTRINSIC SQRT
    INTRINSIC ACOS
    REAL*8 :: cosq
    REAL*8 :: arg1
    REAL*8 :: result1
    REAL*8 :: arg2
    REAL*8 :: result2
! vector
    c1 = x(1) - x(4)
    c2 = x(2) - x(5)
    c3 = x(3) - x(6)
    c4 = x(4) - x(7)
    c5 = x(5) - x(8)
    c6 = x(6) - x(9)
    c7 = x(7) - x(10)
    c8 = x(8) - x(11)
    c9 = x(9) - x(12)
    c10 = x(1) - x(7)
    c11 = x(2) - x(8)
    c12 = x(3) - x(9)
    c13 = x(4) - x(10)
    c14 = x(5) - x(11)
    c15 = x(6) - x(12)
!c16=x(1)-x(10)
!c17=x(2)-x(11)
!c18=x(3)-x(12)
!
! H1 -- O1 -- O2 -- H2
!   rH1O1 rO1O2 rO2H2
! 
!  angle H1O1O2 = AH1OO
!  angle O1O2H2 = AOOH2
!
!  TORSION HOOH = THOOH
    arg1 = c1**2 + c2**2 + c3**2
    rh1o1 = SQRT(arg1)
    arg1 = c4**2 + c5**2 + c6**2
    ro1o2 = SQRT(arg1)
    arg1 = c7**2 + c8**2 + c9**2
    ro2h2 = SQRT(arg1)
! The potential can give weird values for unusual geometries
! replace with some high value in these unphysical regions and
! then exit
!
    n1 = -(c4*c1+c5*c2+c6*c3)
    d1 = ro1o2*rh1o1
    arg1 = n1/d1
    ah1oo = ACOS(arg1)
    n2 = -(c7*c4+c8*c5+c9*c6)
    d2 = ro2h2*ro1o2
    arg1 = n2/d2
    aooh2 = ACOS(arg1)
! Calculate torsion angle HOOH
! X(4) - X(1)
    xcomp1 = -c1
! X(5) - X(2)
    ycomp1 = -c2
! X(6) - X(3)
    zcomp1 = -c3
    xcomp2 = c10
    ycomp2 = c11
    zcomp2 = c12
    x_normal1 = ycomp1*zcomp2 - zcomp1*ycomp2
    y_normal1 = zcomp1*xcomp2 - xcomp1*zcomp2
    z_normal1 = xcomp1*ycomp2 - ycomp1*xcomp2
! X(7) - X(4) 
    xcomp3 = -c4
! X(8) - X(5) 
    ycomp3 = -c5
! X(9) - X(6)
    zcomp3 = -c6
    xcomp4 = c13
    ycomp4 = c14
    zcomp4 = c15
    x_normal2 = ycomp3*zcomp4 - zcomp3*ycomp4
    y_normal2 = zcomp3*xcomp4 - xcomp3*zcomp4
    z_normal2 = xcomp3*ycomp4 - ycomp3*xcomp4
    n = x_normal1*x_normal2 + y_normal1*y_normal2 + z_normal1*z_normal2
    arg1 = x_normal1*x_normal1 + y_normal1*y_normal1 + z_normal1*&
&     z_normal1
    result1 = SQRT(arg1)
    arg2 = x_normal2*x_normal2 + y_normal2*y_normal2 + z_normal2*&
&     z_normal2
    result2 = SQRT(arg2)
    d = result1*result2
    cosq = n/d
    IF (cosq .GT. 1d0) cosq = 1d0
    IF (cosq .LT. -1d0) cosq = -1d0
! in radians
    thooh = ACOS(cosq)
!R1 =  RH1O1              
!R2 =  RO1O2             
!R3 =  RO2H2         
!A1 =  AH1OO          
!A2 =  AOOH2              
!Q6 =  THOOH  
! Q1,Q2, and Q3 represent the stretching modes
! Q4 and Q5  are the bending modes
! Q6 is the torsional mode 
! Q1, Q2, Q3 are dimensionless, Q4, Q5, and Q6 are in radians
    q3 = (ro1o2-rm_oo)/ro1o2
    q1 = (rh1o1-rm_oh)/rh1o1
    q2 = (ro2h2-rm_oh)/ro2h2
    q4 = ah1oo - angle_ooh
    q5 = aooh2 - angle_ooh
    q6 = thooh
    q1p(0) = 1.d0
    q2p(0) = 1.d0
    q3p(0) = 1.d0
    q4p(0) = 1.d0
    q5p(0) = 1.d0
    q6p(0) = 1.d0
    DO i=1,4
! q1**i
      q1p(i) = q1p(i-1)*q1
! q2**i
      q2p(i) = q2p(i-1)*q2
! q3**i
      q3p(i) = q3p(i-1)*q3
! q4**i
      q4p(i) = q4p(i-1)*q4
! q5**i
      q5p(i) = q5p(i-1)*q5
    END DO
! cos(q6) 
    q6p(1) = cosq
! cos2q
    q6p(2) = 2d0*q6p(1)*q6p(1) - 1d0
! cos3q
    q6p(3) = q6p(1)*(2d0*q6p(2)-1d0)
! cos4q
    q6p(4) = 2d0*q6p(2)*q6p(2) - 1d0
    v = zoe
    DO i=1,152
      v = v + coeff(i)*q1p(ind1(i))*q2p(ind2(i))*q3p(ind3(i))*q4p(ind4(i&
&       ))*q5p(ind5(i))*q6p(ind6(i))
    END DO
    RETURN
  END SUBROUTINE SURF
!
! convert internal coordinates to cartesian coordinates
!
  SUBROUTINE H2O2_INTER_TO_CART(r, x)
    IMPLICIT NONE
    REAL*8 :: r(nr)
    REAL*8 :: x(nx)
! R(1) =  RH1O1         in ang             
! R(2) =  RO1O2         in ang  
! R(3) =  RO2H2         in ang     
! R(4) =  H1O1O2        in rad
! R(5) =  O1O2H2        in rad
! R(6) =  H1-O1-O2-H2   in rad
    REAL*8 :: o2e, o1e, h2e, h2f, ef
    INTRINSIC COS
    INTRINSIC SIN
! set O1 as origin
    x(4:6) = 0d0
! set O1O2 as x axis
    x(7) = r(2)
    x(8:9) = 0d0
! set H1 on x-y plane
    x(1) = r(1)*COS(r(4))
    x(2) = r(1)*SIN(r(4))
    x(3) = 0d0
! calculate H2 from dihedral angle
    o2e = r(3)*COS(r(5))
    h2e = r(3)*SIN(r(5))
    o1e = r(2) - o2e
    ef = h2e*COS(r(6))
    h2f = h2e*SIN(r(6))
    x(10) = o1e
    x(11) = ef
    x(12) = h2f
    RETURN
  END SUBROUTINE H2O2_INTER_TO_CART
END MODULE PES_H2O2
