py::class_<VARIABLE<kids_int>>(m, "VarInt", py::dynamic_attr())  //
    .def(py::init<const std::string&, Shape*, const std::string&>())
    .def("name", &VARIABLE<kids_int>::name)
    .def("doc", &VARIABLE<kids_int>::doc)
    .def("shape", &VARIABLE<kids_int>::shape);

py::class_<VARIABLE<kids_real>>(m, "VarReal", py::dynamic_attr())  //
    .def(py::init<const std::string&, Shape*, const std::string&>())
    .def("name", &VARIABLE<kids_real>::name)
    .def("doc", &VARIABLE<kids_real>::doc)
    .def("shape", &VARIABLE<kids_real>::shape);

py::class_<VARIABLE<kids_complex>>(m, "VarComplex", py::dynamic_attr())  //
    .def(py::init<const std::string&, Shape*, const std::string&>())
    .def("name", &VARIABLE<kids_complex>::name)
    .def("doc", &VARIABLE<kids_complex>::doc)
    .def("shape", &VARIABLE<kids_complex>::shape);

py::module data_m                  = m.def_submodule("data");
py::module data_init_m             = data_m.def_submodule("init");
py::module data_integrator_m       = data_m.def_submodule("integrator");
py::module data_integrator_GWP_m   = data_integrator_m.def_submodule("GWP");
py::module data_integrator_nhc_m   = data_integrator_m.def_submodule("nhc");
py::module data_integrator_tmp_m   = data_integrator_m.def_submodule("tmp");
py::module data_integrator_param_m = data_integrator_m.def_submodule("param");
py::module data_flowcontrol_m      = data_m.def_submodule("flowcontrol");
py::module data_last_m             = data_m.def_submodule("last");
py::module data_model_m            = data_m.def_submodule("model");
py::module data_model_bath_m       = data_model_m.def_submodule("bath");
py::module data_model_coupling_m   = data_model_m.def_submodule("coupling");
py::module data_model_rep_m        = data_model_m.def_submodule("rep");
py::module data_random_m           = data_m.def_submodule("random");
py::module data_random_seed_m      = data_model_m.def_submodule("seed");

data_init_m.attr("Etot") = DATA::init::Etot;
data_init_m.attr("p")    = DATA::init::p;
data_init_m.attr("x")    = DATA::init::x;

data_integrator_m.attr("Acoeff") = DATA::integrator::Acoeff;
data_integrator_m.attr("E")      = DATA::integrator::E;
data_integrator_m.attr("Ekin")   = DATA::integrator::Ekin;
data_integrator_m.attr("Epot")   = DATA::integrator::Epot;
data_integrator_m.attr("Etot")   = DATA::integrator::Etot;

data_integrator_GWP_m.attr("L")      = DATA::integrator::GWP::L;
data_integrator_GWP_m.attr("L1")     = DATA::integrator::GWP::L1;
data_integrator_GWP_m.attr("L2")     = DATA::integrator::GWP::L2;
data_integrator_GWP_m.attr("R")      = DATA::integrator::GWP::R;
data_integrator_GWP_m.attr("R1")     = DATA::integrator::GWP::R1;
data_integrator_GWP_m.attr("R2")     = DATA::integrator::GWP::R2;
data_integrator_GWP_m.attr("S1")     = DATA::integrator::GWP::S1;
data_integrator_GWP_m.attr("S1h")    = DATA::integrator::GWP::S1h;
data_integrator_GWP_m.attr("S2")     = DATA::integrator::GWP::S2;
data_integrator_GWP_m.attr("S2h")    = DATA::integrator::GWP::S2h;
data_integrator_GWP_m.attr("Sx")     = DATA::integrator::GWP::Sx;
data_integrator_GWP_m.attr("invS1h") = DATA::integrator::GWP::invS1h;
data_integrator_GWP_m.attr("invS2h") = DATA::integrator::GWP::invS2h;

data_integrator_m.attr("Hbasis")            = DATA::integrator::Hbasis;
data_integrator_m.attr("Hcoeff")            = DATA::integrator::Hcoeff;
data_integrator_m.attr("K0")                = DATA::integrator::K0;
data_integrator_m.attr("K1")                = DATA::integrator::K1;
data_integrator_m.attr("K1DA")              = DATA::integrator::K1DA;
data_integrator_m.attr("K1DD")              = DATA::integrator::K1DD;
data_integrator_m.attr("K1QA")              = DATA::integrator::K1QA;
data_integrator_m.attr("K1QD")              = DATA::integrator::K1QD;
data_integrator_m.attr("K2")                = DATA::integrator::K2;
data_integrator_m.attr("K2DA")              = DATA::integrator::K2DA;
data_integrator_m.attr("K2DD")              = DATA::integrator::K2DD;
data_integrator_m.attr("K2QA")              = DATA::integrator::K2QA;
data_integrator_m.attr("K2QD")              = DATA::integrator::K2QD;
data_integrator_m.attr("K2QD")              = DATA::integrator::KSHA;
data_integrator_m.attr("KTWA")              = DATA::integrator::KTWA;
data_integrator_m.attr("KTWD")              = DATA::integrator::KTWD;
data_integrator_m.attr("OpA")               = DATA::integrator::OpA;
data_integrator_m.attr("OpB")               = DATA::integrator::OpB;
data_integrator_m.attr("P_used")            = DATA::integrator::P_used;
data_integrator_m.attr("S")                 = DATA::integrator::S;
data_integrator_m.attr("Sele")              = DATA::integrator::Sele;
data_integrator_m.attr("Snuc")              = DATA::integrator::Snuc;
data_integrator_m.attr("U")                 = DATA::integrator::U;
data_integrator_m.attr("UXdt")              = DATA::integrator::UXdt;
data_integrator_m.attr("UYdt")              = DATA::integrator::UYdt;
data_integrator_m.attr("Ubranch")           = DATA::integrator::Ubranch;
data_integrator_m.attr("Udt")               = DATA::integrator::Udt;
data_integrator_m.attr("Xcoeff")            = DATA::integrator::Xcoeff;
data_integrator_m.attr("alpha")             = DATA::integrator::alpha;
data_integrator_m.attr("c")                 = DATA::integrator::c;
data_integrator_m.attr("c1")                = DATA::integrator::c1;
data_integrator_m.attr("c2p")               = DATA::integrator::c2p;
data_integrator_m.attr("clone_account")     = DATA::integrator::clone_account;
data_integrator_m.attr("dtAcoeff")          = DATA::integrator::dtAcoeff;
data_integrator_m.attr("dtSele")            = DATA::integrator::dtSele;
data_integrator_m.attr("dtlnSnuc")          = DATA::integrator::dtlnSnuc;
data_integrator_m.attr("f")                 = DATA::integrator::f;
data_integrator_m.attr("fadd")              = DATA::integrator::fadd;
data_integrator_m.attr("g")                 = DATA::integrator::g;
data_integrator_m.attr("invS")              = DATA::integrator::invS;
data_integrator_m.attr("m")                 = DATA::integrator::m;
data_integrator_m.attr("minv")              = DATA::integrator::minv;
data_integrator_nhc_m.attr("G")             = DATA::integrator::nhc::G;
data_integrator_nhc_m.attr("Q")             = DATA::integrator::nhc::Q;
data_integrator_nhc_m.attr("p")             = DATA::integrator::nhc::p;
data_integrator_nhc_m.attr("x")             = DATA::integrator::nhc::x;
data_integrator_m.attr("norm")              = DATA::integrator::norm;
data_integrator_m.attr("occ_nuc")           = DATA::integrator::occ_nuc;
data_integrator_m.attr("ve")                = DATA::integrator::ve;
data_integrator_m.attr("p")                 = DATA::integrator::p;
data_integrator_m.attr("p_sign")            = DATA::integrator::p_sign;
data_integrator_param_m.attr("c1")          = DATA::integrator::param::c1;
data_integrator_param_m.attr("c2p")         = DATA::integrator::param::c2p;
data_integrator_m.attr("pf_cross")          = DATA::integrator::pf_cross;
data_integrator_m.attr("rho_dual")          = DATA::integrator::rho_dual;
data_integrator_m.attr("rho_ele")           = DATA::integrator::rho_ele;
data_integrator_m.attr("rho_nuc")           = DATA::integrator::rho_nuc;
data_integrator_m.attr("rhored")            = DATA::integrator::rhored;
data_integrator_m.attr("rhored2")           = DATA::integrator::rhored2;
data_integrator_m.attr("rhored3")           = DATA::integrator::rhored3;
data_integrator_m.attr("trKTWA")            = DATA::integrator::trKTWA;
data_integrator_m.attr("trKTWD")            = DATA::integrator::trKTWD;
data_integrator_m.attr("sqcw")              = DATA::integrator::sqcw;
data_integrator_m.attr("sqcw0")             = DATA::integrator::sqcw0;
data_integrator_m.attr("sqcwh")             = DATA::integrator::sqcwh;
data_integrator_tmp_m.attr("I_PP")          = DATA::integrator::tmp::I_PP;
data_integrator_tmp_m.attr("MatC_PP")       = DATA::integrator::tmp::MatC_PP;
data_integrator_tmp_m.attr("MatR_PP")       = DATA::integrator::tmp::MatR_PP;
data_integrator_tmp_m.attr("TtTold")        = DATA::integrator::tmp::TtTold;
data_integrator_tmp_m.attr("direction")     = DATA::integrator::tmp::direction;
data_integrator_tmp_m.attr("fproj")         = DATA::integrator::tmp::fproj;
data_integrator_tmp_m.attr("ftmp")          = DATA::integrator::tmp::ftmp;
data_integrator_tmp_m.attr("fun_diag_F")    = DATA::integrator::tmp::fun_diag_F;
data_integrator_tmp_m.attr("fun_diag_P")    = DATA::integrator::tmp::fun_diag_P;
data_integrator_tmp_m.attr("invexpidiagdt") = DATA::integrator::tmp::invexpidiagdt;
data_integrator_tmp_m.attr("ve")            = DATA::integrator::tmp::ve;
data_integrator_tmp_m.attr("vedE")          = DATA::integrator::tmp::vedE;
data_integrator_tmp_m.attr("wrho")          = DATA::integrator::tmp::wrho;
data_integrator_m.attr("veF")               = DATA::integrator::veF;
data_integrator_m.attr("w")                 = DATA::integrator::w;
data_integrator_m.attr("w_AA")              = DATA::integrator::w_AA;
data_integrator_m.attr("w_AD")              = DATA::integrator::w_AD;
data_integrator_m.attr("w_CC")              = DATA::integrator::w_CC;
data_integrator_m.attr("w_CP")              = DATA::integrator::w_CP;
data_integrator_m.attr("w_DD")              = DATA::integrator::w_DD;
data_integrator_m.attr("w_PP")              = DATA::integrator::w_PP;
data_integrator_m.attr("ww_A")              = DATA::integrator::ww_A;
data_integrator_m.attr("ww_D")              = DATA::integrator::ww_D;
data_integrator_m.attr("wz_A")              = DATA::integrator::wz_A;
data_integrator_m.attr("wz_D")              = DATA::integrator::wz_D;
data_integrator_m.attr("x")                 = DATA::integrator::x;
data_integrator_m.attr("xgrid")             = DATA::integrator::xgrid;
data_flowcontrol_m.attr("at_condition")     = DATA::flowcontrol::at_condition;
data_flowcontrol_m.attr("dt")               = DATA::flowcontrol::dt;
data_flowcontrol_m.attr("dtsize")           = DATA::flowcontrol::dtsize;
data_flowcontrol_m.attr("fail_type")        = DATA::flowcontrol::fail_type;
data_flowcontrol_m.attr("frez")             = DATA::flowcontrol::frez;
data_flowcontrol_m.attr("isamp")            = DATA::flowcontrol::isamp;
data_flowcontrol_m.attr("istep")            = DATA::flowcontrol::istep;
data_flowcontrol_m.attr("last_attempt")     = DATA::flowcontrol::last_attempt;
data_flowcontrol_m.attr("msize")            = DATA::flowcontrol::msize;
data_flowcontrol_m.attr("nsamp")            = DATA::flowcontrol::nsamp;
data_flowcontrol_m.attr("nstep")            = DATA::flowcontrol::nstep;
data_flowcontrol_m.attr("sstep")            = DATA::flowcontrol::sstep;
data_flowcontrol_m.attr("succ")             = DATA::flowcontrol::succ;
data_flowcontrol_m.attr("t")                = DATA::flowcontrol::t;
data_flowcontrol_m.attr("tsize")            = DATA::flowcontrol::tsize;
data_last_m.attr("Etot")                    = DATA::last::Etot;
data_last_m.attr("c")                       = DATA::last::c;
data_last_m.attr("dV")                      = DATA::last::dV;
data_last_m.attr("g")                       = DATA::last::g;
data_last_m.attr("grad")                    = DATA::last::grad;
data_last_m.attr("p")                       = DATA::last::p;
data_last_m.attr("x")                       = DATA::last::x;
data_model_m.attr("Hsys")                   = DATA::model::Hsys;
data_model_m.attr("Tmod")                   = DATA::model::Tmod;
data_model_m.attr("V")                      = DATA::model::V;
data_model_m.attr("atoms")                  = DATA::model::atoms;
data_model_bath_m.attr("coeffs")            = DATA::model::bath::coeffs;
data_model_bath_m.attr("omegas")            = DATA::model::bath::omegas;
data_model_coupling_m.attr("CL")            = DATA::model::coupling::CL;
data_model_coupling_m.attr("Q")             = DATA::model::coupling::Q;
data_model_coupling_m.attr("QL")            = DATA::model::coupling::QL;
data_model_m.attr("dV")                     = DATA::model::dV;
data_model_m.attr("ddV")                    = DATA::model::ddV;
data_model_m.attr("f_p")                    = DATA::model::f_p;
data_model_m.attr("f_r")                    = DATA::model::f_r;
data_model_m.attr("f_rp")                   = DATA::model::f_rp;
data_model_m.attr("grad")                   = DATA::model::grad;
data_model_m.attr("hess")                   = DATA::model::hess;
data_model_m.attr("kcoeff")                 = DATA::model::kcoeff;
data_model_m.attr("lcoeff")                 = DATA::model::lcoeff;
data_model_m.attr("mass")                   = DATA::model::mass;
data_model_m.attr("p0")                     = DATA::model::p0;
data_model_m.attr("p_sigma")                = DATA::model::p_sigma;
data_model_rep_m.attr("eig")                = DATA::model::rep::eig;
data_model_rep_m.attr("E")                  = DATA::model::rep::E;
data_model_rep_m.attr("H")                  = DATA::model::rep::H;
data_model_rep_m.attr("lam")                = DATA::model::rep::lam;
data_model_rep_m.attr("R")                  = DATA::model::rep::R;
data_model_rep_m.attr("T")                  = DATA::model::rep::T;
data_model_rep_m.attr("Told")               = DATA::model::rep::Told;
data_model_rep_m.attr("dE")                 = DATA::model::rep::dE;
data_model_rep_m.attr("ddE")                = DATA::model::rep::ddE;
data_model_rep_m.attr("nac")                = DATA::model::rep::nac;
data_model_rep_m.attr("nac_prev")           = DATA::model::rep::nac_prev;
data_model_m.attr("vpes")                   = DATA::model::vpes;
data_model_m.attr("w")                      = DATA::model::w;
data_model_m.attr("x0")                     = DATA::model::x0;
data_model_m.attr("x_sigma")                = DATA::model::x_sigma;
data_random_m.attr("seed")                  = DATA::random::seed;
